<?php
// @loom-file release=0.15.48 revision=16 policy=package-priority
require __DIR__.'/../../api/_common.php';
header('Content-Type: text/html; charset=utf-8');header('Cache-Control: no-store, no-cache, must-revalidate');
$meta=loom_generic_social_meta(loom_absolute_web_url(rtrim(web_base_path(),'/').'/admin/backups/'),'LOOM Backup & Restore','Portable LOOM project migration, export, import, and full-state recovery.');$meta['robots']='noindex,nofollow';$social=loom_social_meta_html($meta,false);
loom_native_admin_page_guard('Backup & Restore','../../');
?><!doctype html><html lang="en"><head><?php echo $social; ?><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><style>
*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,sans-serif;background:#f4f8fb;color:#172231}.wrap{width:min(1240px,calc(100% - 28px));margin:26px auto 70px}.hero,.panel{background:#fff;border:1px solid #d9e4ee;border-radius:22px;box-shadow:0 18px 50px #1722310c}.hero{padding:22px}.eyebrow{font:900 9px/1 system-ui;letter-spacing:.13em;color:#6b7a89}.hero h1{margin:7px 0 5px;font-size:38px;letter-spacing:-.045em}.hero p,.muted{color:#68798b}.nav{display:flex;gap:7px;flex-wrap:wrap;margin-top:14px}.nav a,.btn{border:1px solid #cad9e8;border-radius:11px;background:#fff;color:#1e4e80;padding:9px 11px;font-weight:850;font-size:11px;text-decoration:none;cursor:pointer}.btn.primary{background:#2878d7;color:#fff;border-color:#2878d7}.btn.danger{color:#a12c2c;border-color:#e7bebe}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-top:14px}.panel{padding:18px}.panel h2{margin:0 0 6px}.option{border:1px solid #dce6ef;border-radius:15px;padding:14px;margin-top:10px;background:#fbfdff}.option b{display:block}.option p{font-size:11px;margin:5px 0 10px;color:#6b7b8c;line-height:1.5}.field{margin-top:10px}.field label{display:block;font:850 10px/1.2 system-ui;margin-bottom:6px}.field select,.field input{width:100%;padding:10px;border:1px solid #cddae6;border-radius:10px;background:#fff}.msg{margin-top:10px;font-size:11px;white-space:pre-wrap}.table{overflow:auto;margin-top:10px}.table table{width:100%;border-collapse:collapse;font-size:10px}.table th,.table td{padding:9px;border-bottom:1px solid #edf2f6;text-align:left;white-space:nowrap}.pill{display:inline-block;padding:4px 7px;border-radius:999px;background:#edf4fb;font-weight:800;font-size:9px}.warn{background:#fff7e7;border:1px solid #f0d9a4;border-radius:12px;padding:10px;font-size:10px;color:#73581f;margin-top:10px}.ok{color:#16704f}.bad{color:#aa3131}.actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}@media(max-width:800px){.grid{grid-template-columns:1fr}.wrap{width:calc(100% - 14px)}}
</style></head><body><div id="loomShellHeader"></div><main class="wrap"><section class="hero"><div class="eyebrow">LOOM ADMIN · PORTABILITY & RECOVERY</div><h1>Export, Import & Restore</h1><p>Move projects between LOOM installations, create data-bearing backups, or capture the entire persistent LOOM state without shipping database credentials or live auth sessions.</p><div class="nav"><a href="../">Admin</a><a href="../../home/">LOOM Home</a></div></section>
<div class="grid"><section class="panel"><h2>Export</h2><div class="field"><label>Project</label><select id="project"><option>Loading projects…</option></select></div>
<div class="option"><b>Project only</b><p>Project runtime, branding, module settings, overlays and project assets. Excludes users, telemetry, referrals, sessions and project data. Best for sharing or moving a project.</p><button class="btn primary" data-export="project">Export Project</button></div>
<div class="option"><b>Project + data</b><p>Everything above plus project-owned Instance Vault state, uploads and project-scoped durable data.</p><button class="btn" data-export="project-data">Export Project + Data</button></div>
<div class="option"><b>All projects</b><p>Every project structure/configuration without server-unique project data.</p><button class="btn" data-export="projects">Export All Projects</button></div>
<div class="option"><b>All projects + data</b><p>Every project plus project-owned Instance Vault data. Requires LOOM Admin access.</p><button class="btn" data-export="projects-data">Export All Projects + Data</button></div>
<div class="option"><b>Full LOOM state</b><p>System Owner only. Captures persistent Instance state plus portable database application data when a LOOM database is available. Database connection credentials, active auth sessions and server secrets are intentionally excluded.</p><div class="warn"><b>Portable, not reckless:</b> full backups may contain password hashes needed to restore permanent accounts, but never plaintext passwords, active auth sessions, database credentials, or server secrets. Database payloads can be staged until the destination has a configured database.</div><button class="btn danger" data-export="full">Export Full LOOM State</button></div><div id="exportMsg" class="msg"></div></section>
<section class="panel" id="importPanel"><h2>Import bundle</h2><p class="muted">Upload a LOOM portable ZIP. LOOM verifies every declared checksum before showing a preview. Nothing is applied during upload.</p><input id="bundle" type="file" accept=".zip,application/zip"><div class="actions"><button id="preview" class="btn primary">Upload + Preview</button></div><div id="importPreview" class="msg"></div><div id="importActions" style="display:none"><div id="projectMappings"></div><div class="field"><label>Default conflict strategy</label><select id="strategy"><option value="create-new">Create new only</option><option value="merge">Merge safely</option><option value="replace">Replace existing project/state</option><option value="skip">Skip conflicts</option></select></div><div id="fullConfirm" class="field" style="display:none"><label>Full restore confirmation</label><input id="confirm" placeholder="Type RESTORE LOOM"></div><div class="actions"><button id="apply" class="btn danger">Apply Import</button></div></div></section></div>
<section class="panel" style="margin-top:14px"><h2>Generated backups</h2><p class="muted">Generated bundles stay on protected Instance storage until downloaded or cleaned up.</p><div id="backups" class="table"><div class="muted">Loading…</div></div><h3>Pending database payloads</h3><p class="muted">If a full bundle was restored before a destination database was configured, its portable database payload waits here safely.</p><div id="pending" class="table"></div></section></main><div id="loomShellFooter"></div>
<script src="../../engine/deployment-guard.js?v=0.15.48"></script><script src="../../engine/loom-brand.js?v=0.15.48"></script><script src="../../engine/identity.js?v=0.15.48"></script><script src="../../engine/loom-global-profile.js?v=0.15.48"></script><script src="../../engine/loom-toast.js?v=0.15.48"></script><script src="../../engine/share-referrals.js?v=0.15.48"></script><script src="../../engine/loom-shell.js?v=0.15.48"></script><script>
const identity=LoomIdentity.get('loom-admin-backups'),$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let previewState=null;
async function jsonFetch(url,opts={}){const r=await fetch(url,{cache:'no-store',...opts});const txt=await r.text();let j;try{j=JSON.parse(txt)}catch{throw new Error(`Server returned ${r.status} ${r.statusText} instead of JSON.`)}if(!r.ok||j.ok===false)throw new Error(j.error||`Request failed (${r.status})`);return j}
async function post(body){return jsonFetch('../../api/backup.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:identity.clientId,...body})})}
async function loadProjects(){const j=await jsonFetch(`../../api/projects.php?clientId=${encodeURIComponent(identity.clientId)}&_=${Date.now()}`);const rows=j.projects||[];$('#project').innerHTML=rows.map(p=>`<option value="${esc(p.slug||p.project)}">${esc(p.name||p.slug||p.project)}</option>`).join('')||'<option value="">No projects</option>'}
async function loadBackups(){try{const j=await post({action:'list'}),rows=j.backups||[];$('#backups').innerHTML=rows.length?`<table><thead><tr><th>Created</th><th>Type</th><th>Scope</th><th>Size</th><th>Actions</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(new Date(x.createdAt).toLocaleString())}</td><td><span class="pill">${esc(x.type)}</span></td><td><b>${esc(x.scopeLabel||(x.project||'LOOM'))}</b>${x.project?`<br><code>${esc(x.project)}</code>`:''}</td><td>${(Number(x.size||0)/1048576).toFixed(2)} MB</td><td><a class="btn" href="${esc(x.downloadUrl)}">Download</a> <button class="btn danger" data-delete="${esc(x.backupId)}">Delete</button></td></tr>`).join('')}</tbody></table>`:'<div class="muted">No generated backups yet.</div>';document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this generated backup?'))return;await post({action:'delete',id:b.dataset.delete});loadBackups()});const pending=j.pendingDatabase||[];$('#pending').innerHTML=pending.length?`<table><thead><tr><th>Created</th><th>Tables</th><th>Size</th><th>Action</th></tr></thead><tbody>${pending.map(x=>`<tr><td>${esc(new Date(x.createdAt).toLocaleString())}</td><td>${esc(x.tableCount)}</td><td>${(Number(x.size||0)/1048576).toFixed(2)} MB</td><td><button class="btn" data-db="${esc(x.id)}">Apply to configured DB</button></td></tr>`).join('')}</tbody></table>`:'<div class="muted">No staged database payloads.</div>';document.querySelectorAll('[data-db]').forEach(b=>b.onclick=async()=>{try{const j=await post({action:'apply-pending-db',id:b.dataset.db,strategy:'merge'});LoomToast?.success?.(`Database payload ${j.result.status}.`);loadBackups()}catch(e){LoomToast?.error?.(e.message)}})}catch(e){$('#backups').innerHTML=`<div class="bad">${esc(e.message)}</div>`}}
document.querySelectorAll('[data-export]').forEach(b=>b.onclick=async()=>{const type=b.dataset.export,project=$('#project').value,projectScoped=type==='project'||type==='project-data';$('#exportMsg').textContent='Building verified bundle…';try{if(type==='full'&&!confirm('Create a full LOOM state backup? This is installation-wide and can contain sensitive user/application data (but not DB credentials or active auth sessions).'))return;const request={action:'create',type};if(projectScoped)request.project=project;const j=await post(request);$('#exportMsg').innerHTML=`<span class="ok">Created ${esc(j.backup.backupId)} · ${esc(j.backup.scopeLabel||'LOOM')} · ${(Number(j.backup.size||0)/1048576).toFixed(2)} MB</span> <a class="btn" href="${esc(j.backup.downloadUrl)}">Download</a>`;loadBackups()}catch(e){$('#exportMsg').innerHTML=`<span class="bad">${esc(e.message)}</span>`}});
$('#preview').onclick=async()=>{const f=$('#bundle').files[0];if(!f)return LoomToast?.required?.('Choose a LOOM bundle first.');const fd=new FormData();fd.append('clientId',identity.clientId);fd.append('bundle',f);$('#importPreview').textContent='Uploading and verifying…';try{const j=await jsonFetch('../../api/backup.php',{method:'POST',body:fd});previewState=j.preview;const p=j.preview;$('#importPreview').innerHTML=`<b>Verified bundle</b><br>Type: ${esc(p.exportType)} · Source LOOM ${esc(p.sourceLoomVersion||'?')}<br>Projects: ${(p.projects||[]).length}<br>Database: ${p.database?.included?'portable payload included':'not included'}<br>Checksums: ${p.verification?.checked||0} verified`;$('#projectMappings').innerHTML=(p.projects||[]).map(x=>`<div class="option" data-map-source="${esc(x.slug)}"><b>${esc(x.name)}</b><p>Source slug <code>${esc(x.slug)}</code> · ${x.exists?`A ${esc(x.currentSource||'current')} project already uses this slug.`:'No current conflict.'}${x.htmlFramerIncluded?` · HTML Framer: ${esc(x.htmlFramerFrameCount||0)} frame package${Number(x.htmlFramerFrameCount||0)===1?'':'s'} included.`:''}</p><div class="field"><label>Destination Instance Project slug</label><input data-map-target value="${esc(x.slug)}"></div><div class="field"><label>Strategy for this project</label><select data-map-strategy><option value="create-new" ${x.exists?'':'selected'}>Create new only</option><option value="merge" ${x.exists?'selected':''}>Merge safely</option><option value="replace">Replace existing</option><option value="skip">Skip</option></select></div></div>`).join('');$('#importActions').style.display='block';$('#fullConfirm').style.display=p.requiresSystemOwner?'block':'none'}catch(e){$('#importPreview').innerHTML=`<span class="bad">${esc(e.message)}</span>`}}
$('#apply').onclick=async()=>{if(!previewState)return;const projectMap={},projectStrategies={};document.querySelectorAll('[data-map-source]').forEach(row=>{projectMap[row.dataset.mapSource]=row.querySelector('[data-map-target]').value.trim();projectStrategies[row.dataset.mapSource]=row.querySelector('[data-map-strategy]').value});const body={action:'apply',importId:previewState.importId,strategy:$('#strategy').value,confirm:$('#confirm').value,projectMap,projectStrategies};try{const j=await post(body);$('#importPreview').innerHTML=`<span class="ok"><b>Import complete.</b></span><pre>${esc(JSON.stringify(j.result,null,2))}</pre>`;$('#importActions').style.display='none';loadBackups()}catch(e){$('#importPreview').innerHTML=`<span class="bad">${esc(e.message)}</span>`}}
(async()=>{try{await LoomShell?.mount?.({apiBase:'../../api',identity,pageTitle:'Backup & Restore',links:[{label:'Admin',href:'../'},{label:'LOOM Home',href:'../../home/'}]});await loadProjects();await loadBackups();if(new URLSearchParams(location.search).get('mode')==='import'){document.getElementById('importPanel')?.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>document.getElementById('bundle')?.focus(),250)}}catch(e){document.body.innerHTML=`<div style="padding:30px;font-family:system-ui"><h1>Backup & Restore failed</h1><p>${esc(e.message)}</p><a href="../">Return to Admin</a></div>`}})();
</script></body></html>
