<?php
// @loom-file release=0.15.55 revision=25 policy=package-priority
declare(strict_types=1);
function loom_public_page(string $title,string $description,string $body,string $path,bool $requireIdentity=true,bool $sensitive=false): never {
  require_once __DIR__.'/api/_common.php';
  $meta=loom_generic_social_meta(loom_absolute_web_url(rtrim(web_base_path(),'/').'/'.ltrim($path,'/')),$title,$description);
  header('Content-Type: text/html; charset=utf-8');header('Cache-Control: '.($sensitive?'no-store, max-age=0':'no-cache, must-revalidate, max-age=0'));if($sensitive)header('Referrer-Policy: no-referrer');
  $social=loom_social_meta_html($meta,false);$base=rtrim(web_base_path(),'/');$safeTitle=htmlspecialchars($title,ENT_QUOTES,'UTF-8');
  $entryScript=$requireIdentity?'<script src="'.htmlspecialchars($base.'/engine/identity-entry.js?v=0.15.55',ENT_QUOTES).'"></script>':'';
  $entryEnsure=$requireIdentity?'await window.LoomIdentityEntry?.ensure?.();':'';
  echo '<!doctype html><html lang="en"><head>'.$social.'<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><link rel="icon" type="image/png" href="'.htmlspecialchars($base.'/assets/loom-logo.png',ENT_QUOTES).'"><style>'.loom_public_page_css().'</style></head><body><div id="loomShellHeader"></div><main><div class="eyebrow">LOOM · PUBLIC</div><h1>'.$safeTitle.'</h1><p class="lead">'.htmlspecialchars($description,ENT_QUOTES).'</p>'.$body.'</main><div id="loomShellFooter"></div><script src="'.htmlspecialchars($base.'/engine/deployment-guard.js?v=0.15.55',ENT_QUOTES).'"></script><script src="'.htmlspecialchars($base.'/engine/identity.js?v=0.15.55',ENT_QUOTES).'"></script>'.$entryScript.'<script src="'.htmlspecialchars($base.'/engine/loom-brand.js?v=0.15.55',ENT_QUOTES).'"></script><script src="'.htmlspecialchars($base.'/engine/loom-global-profile.js?v=0.15.55',ENT_QUOTES).'"></script><script src="'.htmlspecialchars($base.'/engine/loom-toast.js?v=0.15.55',ENT_QUOTES).'"></script><script src="'.htmlspecialchars($base.'/engine/share-referrals.js?v=0.15.55',ENT_QUOTES).'"></script><script src="'.htmlspecialchars($base.'/engine/loom-shell.js?v=0.15.55',ENT_QUOTES).'"></script><script>(async()=>{'.$entryEnsure.'const identity=window.LoomIdentity?.get?.("loom-public");await window.LoomShell?.mount?.({apiBase:"'.htmlspecialchars($base.'/api',ENT_QUOTES).'",identity,pageTitle:'.json_encode($title,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT).',links:[{label:"About",href:"'.htmlspecialchars($base.'/about',ENT_QUOTES).'"},{label:"Docs",href:"'.htmlspecialchars($base.'/docs/',ENT_QUOTES).'"}]})})().catch(()=>{})</script></body></html>';exit;
}
function loom_public_page_css(): string { return '*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,-apple-system,sans-serif;background:#f5faf6;color:#132019}main{width:min(960px,calc(100% - 30px));margin:58px auto 70px}.eyebrow{font-size:10px;font-weight:900;letter-spacing:.14em;color:#5e7665}h1{font-size:clamp(38px,7vw,72px);letter-spacing:-.055em;margin:8px 0}.lead{font-size:18px;line-height:1.6;color:#607067;max-width:760px}.card{margin-top:24px;background:white;border:1px solid #dfe9e1;border-radius:22px;padding:22px;box-shadow:0 18px 50px #173c240d}.card h2{margin-top:0}.card p,.card li{line-height:1.7;color:#53655a}.card a{color:#116b39}code{background:#edf6ef;padding:2px 5px;border-radius:5px}@media(max-width:620px){main{margin-top:36px}}'; }
