<?php
// @loom-file release=0.15.26 revision=1 policy=package-priority
declare(strict_types=1);
function loom_public_page(string $title,string $description,string $body,string $path): never {
  require_once __DIR__.'/api/_common.php';
  $meta=loom_generic_social_meta(loom_absolute_web_url(rtrim(web_base_path(),'/').'/'.ltrim($path,'/')),$title,$description);
  header('Content-Type: text/html; charset=utf-8');header('Cache-Control: no-cache, must-revalidate, max-age=0');
  $social=loom_social_meta_html($meta,false);$base=rtrim(web_base_path(),'/');
  echo '<!doctype html><html lang="en"><head>'.$social.'<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><link rel="icon" type="image/png" href="'.htmlspecialchars($base.'/assets/loom-logo.png',ENT_QUOTES).'"><style>'.loom_public_page_css().'</style></head><body><header class="top"><a class="brand" href="'.htmlspecialchars($base.'/home/',ENT_QUOTES).'"><img src="'.htmlspecialchars($base.'/assets/loom-logo.png',ENT_QUOTES).'" alt=""><b>LOOM</b></a><nav><a href="'.htmlspecialchars($base.'/home/',ENT_QUOTES).'">Home</a><a href="'.htmlspecialchars($base.'/about',ENT_QUOTES).'">About</a><a href="'.htmlspecialchars($base.'/docs/',ENT_QUOTES).'">Docs</a><button id="share">🔗 Share</button></nav></header><main><div class="eyebrow">LOOM · PUBLIC</div><h1>'.htmlspecialchars($title,ENT_QUOTES).'</h1><p class="lead">'.htmlspecialchars($description,ENT_QUOTES).'</p>'.$body.'</main><footer><strong>Powered by LOOM</strong><div><a href="'.htmlspecialchars($base.'/privacy',ENT_QUOTES).'">Privacy</a> · <a href="'.htmlspecialchars($base.'/terms',ENT_QUOTES).'">Terms</a></div></footer><script src="'.htmlspecialchars($base.'/engine/deployment-guard.js?v=0.15.26',ENT_QUOTES).'"></script><script src="'.htmlspecialchars($base.'/engine/identity.js?v=0.15.26',ENT_QUOTES).'"></script><script src="'.htmlspecialchars($base.'/engine/loom-brand.js?v=0.15.26',ENT_QUOTES).'"></script><script src="'.htmlspecialchars($base.'/engine/share-referrals.js?v=0.15.26',ENT_QUOTES).'"></script><script>(async()=>{const i=window.LoomIdentity?.get?.("loom-public");await window.LoomShare?.init?.({identity:i,apiBase:"'.htmlspecialchars($base.'/api',ENT_QUOTES).'"});const b=document.getElementById("share");if(b&&window.LoomShare)window.LoomShare.bindButton(b,{identity:i,apiBase:"'.htmlspecialchars($base.'/api',ENT_QUOTES).'",targetUrl:location.href,title:document.title})})()</script></body></html>';exit;
}
function loom_public_page_css(): string { return '*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,-apple-system,sans-serif;background:#f5faf6;color:#132019}.top{position:sticky;top:0;z-index:10;display:flex;align-items:center;justify-content:space-between;gap:16px;padding:12px max(16px,calc((100vw - 1040px)/2));background:#ffffffef;backdrop-filter:blur(14px);border-bottom:1px solid #dfe9e1}.brand{display:flex;align-items:center;gap:8px;color:#173c24;text-decoration:none}.brand img{width:30px;height:30px;object-fit:contain}.top nav{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.top a,.top button{border:1px solid #d7e5da;background:white;color:#245b36;border-radius:10px;padding:8px 10px;text-decoration:none;font:800 11px/1 system-ui;cursor:pointer}main{width:min(960px,calc(100% - 30px));margin:58px auto 70px}.eyebrow{font-size:10px;font-weight:900;letter-spacing:.14em;color:#5e7665}h1{font-size:clamp(38px,7vw,72px);letter-spacing:-.055em;margin:8px 0}.lead{font-size:18px;line-height:1.6;color:#607067;max-width:760px}.card{margin-top:24px;background:white;border:1px solid #dfe9e1;border-radius:22px;padding:22px;box-shadow:0 18px 50px #173c240d}.card h2{margin-top:0}.card p,.card li{line-height:1.7;color:#53655a}.card a{color:#116b39}code{background:#edf6ef;padding:2px 5px;border-radius:5px}footer{width:min(960px,calc(100% - 30px));margin:0 auto 30px;padding:18px 0;border-top:1px solid #dfe9e1;display:flex;justify-content:space-between;color:#68786e;font-size:11px}footer a{color:inherit}@media(max-width:620px){.top{align-items:flex-start}.top nav{justify-content:flex-end}.top nav a{display:none}main{margin-top:36px}footer{flex-direction:column;gap:8px}}'; }
