// @loom-file release=0.12.08 revision=1 policy=package-priority
(() => {
 'use strict';
 function sensitive(el){if(!el)return true;const type=String(el.type||'').toLowerCase();if(type==='password'||type==='hidden')return true;if(el.closest?.('[data-loom-private],[data-loom-sensitive]'))return true;const n=String(el.name||el.id||'').toLowerCase();return /(password|passcode|secret|token|credit|card|ssn|social|auth)/.test(n)}
 function selector(el){if(!el||el===document)return null;if(el.id)return '#'+CSS.escape(el.id);const parts=[];let n=el;for(let i=0;n&&n.nodeType===1&&i<4;i++,n=n.parentElement){let x=n.tagName.toLowerCase();if(n.dataset?.module)x+=`[data-module="${String(n.dataset.module).replace(/"/g,'')}"]`;else if(n.classList?.length)x+='.'+[...n.classList].slice(0,2).map(c=>CSS.escape(c)).join('.');parts.unshift(x)}return parts.join('>')}
 function start({project,identity,runtimeId,apiBase}){if(!project||!identity?.clientId||!identity?.sessionId)return()=>{};let queue=[],timer=null,lastMove=0;const push=e=>{queue.push({t:Date.now(),...e});if(queue.length>=40)flush();else if(!timer)timer=setTimeout(flush,1800)};const flush=async()=>{clearTimeout(timer);timer=null;if(!queue.length)return;const events=queue.splice(0);try{await fetch(`${apiBase}/replay.php`,{method:'POST',headers:{'Content-Type':'application/json'},keepalive:true,body:JSON.stringify({project,clientId:identity.clientId,sessionId:identity.sessionId,userId:identity.userId||null,runtimeId,events})})}catch{}};
 const click=e=>push({type:e.pointerType==='touch'?'tap':'pointer',x:Math.round(e.clientX),y:Math.round(e.clientY),button:e.button,target:selector(e.target)});
 const move=e=>{if(Date.now()-lastMove<120)return;lastMove=Date.now();push({type:'pointer-move',x:Math.round(e.clientX),y:Math.round(e.clientY)})};
 let scrollTimer=null;const scroll=()=>{clearTimeout(scrollTimer);scrollTimer=setTimeout(()=>push({type:'scroll',x:Math.round(scrollX),y:Math.round(scrollY)}),90)};
 const input=e=>{const el=e.target;if(!(el instanceof HTMLInputElement||el instanceof HTMLTextAreaElement||el instanceof HTMLSelectElement))return;const isSensitive=sensitive(el);let value=null;if(!isSensitive){if(el instanceof HTMLSelectElement)value=el.value;else if(el.type==='checkbox'||el.type==='radio')value=!!el.checked;else value=String(el.value||'').slice(0,160)}push({type:'input',target:selector(el),inputType:String(el.type||el.tagName).toLowerCase(),masked:isSensitive,value:isSensitive?'[MASKED]':value})};
 const key=e=>{if(sensitive(e.target))return;push({type:'key',key:['Enter','Escape','Tab','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)?e.key:'text-key',target:selector(e.target)})};
 addEventListener('pointerdown',click,true);addEventListener('pointermove',move,{capture:true,passive:true});addEventListener('scroll',scroll,{capture:true,passive:true});addEventListener('input',input,true);addEventListener('keydown',key,true);push({type:'viewport',width:innerWidth,height:innerHeight,dpr:devicePixelRatio||1,path:location.pathname});
 return()=>{removeEventListener('pointerdown',click,true);removeEventListener('pointermove',move,true);removeEventListener('scroll',scroll,true);removeEventListener('input',input,true);removeEventListener('keydown',key,true);flush()}}
 window.LoomInteractionCapture=Object.freeze({start});
})();
