<?php
// @loom-file release=0.15.75 revision=42 policy=package-priority
require __DIR__.'/../../api/_common.php';
header('Content-Type: text/html; charset=utf-8');header('Cache-Control: no-store, no-cache, must-revalidate');
$meta=loom_generic_social_meta(loom_absolute_web_url(rtrim(web_base_path(),'/').'/admin/referrals/'),'LOOM Referrals','LOOM administrative sharing and referral analytics.');$meta['robots']='noindex,nofollow';$social=loom_social_meta_html($meta,false);
loom_native_admin_page_guard('Referrals','../../');
?><!doctype html><html lang="en"><head><link rel="stylesheet" href="../../engine/loom-design.css?v=0.15.75"><?php echo $social; ?><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><style>
*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,sans-serif;background:#f4f9f5;color:#142118}.wrap{width:min(1240px,calc(100% - 28px));margin:28px auto 60px}.hero,.panel{background:white;border:1px solid #dbe8de;border-radius:24px;box-shadow:0 18px 50px #173c240c}.hero{padding:22px}.eyebrow{font:900 9px/1 system-ui;letter-spacing:.13em;color:#607568}.hero h1{font-size:38px;letter-spacing:-.045em;margin:7px 0}.hero p{color:#66766b;margin:0}.stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:14px 0}.stat{background:#fff;border:1px solid #dbe8de;border-radius:16px;padding:14px}.stat b{display:block;font-size:26px}.stat span{font-size:9px;text-transform:uppercase;letter-spacing:.09em;color:#708078;font-weight:900}.panel{margin-top:14px;overflow:hidden}.panel h2{padding:16px 18px;margin:0;border-bottom:1px solid #e5eee7}.table{overflow:auto}.table table{width:100%;border-collapse:collapse;font-size:11px}.table th,.table td{padding:10px 12px;border-bottom:1px solid #edf2ee;text-align:left;white-space:nowrap}.table th{font-size:8px;text-transform:uppercase;letter-spacing:.08em;color:#748078;background:#f8fbf8}.empty{padding:24px;color:#718077}.code{font:700 9px/1.4 ui-monospace,monospace}.nav{display:flex;gap:7px;flex-wrap:wrap;margin-top:14px}.nav a{padding:8px 10px;border:1px solid #d5e4d8;border-radius:10px;text-decoration:none;color:#235b36;font-weight:850;font-size:10px}@media(max-width:700px){.stats{grid-template-columns:repeat(2,1fr)}.wrap{width:calc(100% - 14px)}}

/* 0.15.75 shared admin utility polish */
body.loom-admin-utility{min-height:100vh;background:radial-gradient(circle at 15% -8%,rgba(169,223,79,.12),transparent 30%),linear-gradient(180deg,#f8fbf8,#eef5f0);color:#142019}
.loom-admin-utility .wrap{width:min(1280px,calc(100% - 32px));margin:30px auto 72px}
.loom-admin-utility .hero,.loom-admin-utility .panel{border-color:rgba(51,103,65,.12)!important;border-radius:22px!important;background:#fff!important;box-shadow:0 12px 40px rgba(18,54,29,.055),inset 0 1px rgba(255,255,255,.95)!important}
.loom-admin-utility .hero{padding:25px!important}.loom-admin-utility .hero h1{font-size:clamp(34px,4vw,44px)!important;letter-spacing:-.05em!important;line-height:1.02}
.loom-admin-utility .panel{padding:20px!important}.loom-admin-utility .nav a,.loom-admin-utility .btn,.loom-admin-utility .tab{min-height:40px;display:inline-flex;align-items:center;justify-content:center;border-radius:10px!important;transition:transform .14s ease,border-color .14s ease,box-shadow .14s ease}
.loom-admin-utility .nav a:hover,.loom-admin-utility .btn:hover:not(:disabled),.loom-admin-utility .tab:hover:not(:disabled){transform:translateY(-1px);box-shadow:0 6px 16px rgba(18,54,29,.07)}
.loom-admin-utility input,.loom-admin-utility select,.loom-admin-utility textarea{min-height:44px;border-radius:10px!important;outline:none;transition:border-color .14s ease,box-shadow .14s ease}.loom-admin-utility input:focus,.loom-admin-utility select:focus,.loom-admin-utility textarea:focus{border-color:#7fbd92!important;box-shadow:0 0 0 4px rgba(22,131,70,.09)}
.loom-admin-utility .option,.loom-admin-utility .usercard,.loom-admin-utility .stat{border-color:rgba(51,103,65,.11)!important;background:#fbfdfb!important}
@media(max-width:760px){.loom-admin-utility .wrap{width:min(100% - 18px,1280px);margin-top:14px}.loom-admin-utility .hero,.loom-admin-utility .panel{padding:18px!important;border-radius:18px!important}}

</style></head><body class="loom-admin-utility loom-referrals-page"><div id="loomShellHeader"></div><main class="wrap"><section class="hero"><div class="eyebrow">LOOM ADMIN · SHARING NETWORK</div><h1>Referrals</h1><p>Permanent referral attribution for guest identities and permanent accounts, generated from canonical LOOM share links.</p><div class="nav"><a href="../">Admin</a><a href="../../home/">LOOM Home</a></div></section><div id="stats" class="stats"></div><section class="panel"><h2>Share links</h2><div id="shares" class="table"><div class="empty">Loading…</div></div></section><section class="panel"><h2>Recent attributed referrals</h2><div id="refs" class="table"><div class="empty">Loading…</div></div></section></main><div id="loomShellFooter"></div>
<script src="../../engine/deployment-guard.js?v=0.15.75"></script><script src="../../engine/loom-time.js?v=0.15.75"></script><script src="../../engine/loom-brand.js?v=0.15.75"></script><script src="../../engine/identity.js?v=0.15.75"></script><script src="../../engine/loom-global-profile.js?v=0.15.75"></script><script src="../../engine/loom-toast.js?v=0.15.75"></script><script src="../../engine/share-referrals.js?v=0.15.75"></script><script src="../../engine/loom-shell.js?v=0.15.75"></script>
<script>
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=v=>v?new Date(v).toLocaleString():'—';const identity=LoomIdentity.get('loom-admin-referrals');
async function load(){const r=await fetch(`../../api/referrals.php?action=admin-list&clientId=${encodeURIComponent(identity.clientId)}&_=${Date.now()}`,{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||`API ${r.status}`);const s=j.stats||{};document.getElementById('stats').innerHTML=[['Share links',s.shareLinks],['Link opens',s.clicks],['Unique visitors',s.uniqueVisitors],['Self opens',s.selfVisits],['Referrals',s.referrals]].map(([k,v])=>`<div class="stat"><b>${Number(v||0)}</b><span>${esc(k)}</span></div>`).join('');const shares=s.shares||[];document.getElementById('shares').innerHTML=shares.length?`<table><thead><tr><th>Created</th><th>Project</th><th>Referrer</th><th>Clicks</th><th>Visitors</th><th>Self opens</th><th>Referrals</th><th>Code</th></tr></thead><tbody>${shares.map(x=>`<tr><td>${esc(fmt(x.createdAt))}</td><td>${esc(x.project||'LOOM')}</td><td>${esc(x.referrerUsername||'LOOM User')}</td><td>${Number(x.clicks||0)}</td><td>${Number(x.uniqueVisitors||0)}</td><td>${Number(x.selfVisits||0)}</td><td>${Number(x.referrals||0)}</td><td class="code">${esc(x.code)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No share links yet.</div>';const refs=s.recentReferrals||[];document.getElementById('refs').innerHTML=refs.length?`<table><thead><tr><th>Attributed</th><th>Project</th><th>Referrer</th><th>Visitor</th><th>Share</th></tr></thead><tbody>${refs.map(x=>`<tr><td>${esc(fmt(x.createdAt))}</td><td>${esc(x.project||'LOOM')}</td><td>${esc(x.referrer?.username||'LOOM User')}</td><td>${esc(x.visitor?.username||x.visitor?.guestId||'Guest')}</td><td class="code">${esc(x.shareCode)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No attributed referrals yet.</div>'}
(async()=>{try{await LoomShare?.init?.({identity,apiBase:'../../api'});await LoomShell?.mount?.({apiBase:'../../api',identity,pageTitle:'Referrals',links:[{label:'Admin',href:'../'},{label:'LOOM Home',href:'../../home/'}]});await load()}catch(e){document.getElementById('shares').innerHTML=`<div class="empty">${esc(e.message)}</div>`}})();
</script></body></html>
