<?php
// @loom-file release=0.12.08 revision=1 policy=package-priority
declare(strict_types=1);
function loom_capability_secret_file(): string { ensure_dir(loom_admin_settings_dir());return loom_admin_settings_dir().'/capability-secret.json'; }
function loom_capability_secret(): string { $p=read_json_file(loom_capability_secret_file())?:[];$v=(string)($p['secret']??'');if(strlen($v)<32){$v=bin2hex(random_bytes(32));@file_put_contents(loom_capability_secret_file(),json_encode(['secret'=>$v,'createdAt'=>server_timestamp()],JSON_PRETTY_PRINT),LOCK_EX);}@chmod(loom_capability_secret_file(),0600);return $v; }
function loom_module_manifest_by_action(string $project,string $actionId): ?array { $actionId=(string)$actionId;foreach(loom_core_module_records('project') as $r){if(($r['manifest']['action']['id']??'')===$actionId)return $r['manifest'];}$dir=project_dir($project);if(!$dir)return null;$root=$dir.'/actions';if(!is_dir($root))return null;$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS));foreach($it as $f){if(!$f->isFile()||$f->getFilename()!=='manifest.json')continue;$m=read_json_file($f->getPathname());if(($m['action']['id']??'')===$actionId)return $m;}return null; }
function loom_capability_declared(string $project,string $actionId,string $capability): bool { $m=loom_module_manifest_by_action($project,$actionId);if(!$m)return false;$c=$m['capabilities']??[];foreach(['requires','permissions'] as $bucket)foreach(($c[$bucket]??[]) as $row){$name=is_array($row)?($row['id']??$row['name']??''):$row;if($name===$capability)return true;}return false; }
function loom_capability_issue(string $project,string $actionId,string $clientId,string $capability,int $ttl=300): array { $project=safe_slug($project);$clientId=safe_token($clientId);if(!$project||!$clientId||!loom_capability_declared($project,$actionId,$capability))throw new RuntimeException('Capability was not declared by this module.');$exp=time()+max(30,min(900,$ttl));$payload=['project'=>$project,'actionId'=>$actionId,'clientId'=>$clientId,'capability'=>$capability,'exp'=>$exp,'nonce'=>bin2hex(random_bytes(8))];$raw=rtrim(strtr(base64_encode(json_encode($payload)),'+/','-_'),'=');$sig=hash_hmac('sha256',$raw,loom_capability_secret());return ['token'=>$raw.'.'.$sig,'expiresAt'=>gmdate('c',$exp),'capability'=>$capability]; }
function loom_capability_contract_status(string $project,array $modules): array { $provided=[];foreach($modules as $m)foreach(($m['capabilities']['provides']??[]) as $r){$id=is_array($r)?($r['id']??''):$r;if($id!=='')$provided[$id][]=$m['action']['id']??'';}foreach($modules as &$m){$missing=[];foreach(($m['capabilities']['requires']??[]) as $r){$id=is_array($r)?($r['id']??''):$r;$optional=is_array($r)?(bool)($r['optional']??false):false;if($id!==''&&!isset($provided[$id])&&!$optional)$missing[]=$id;}$m['capability_health']=['ok'=>!$missing,'missing'=>$missing];}unset($m);return $modules; }
