<?php
// @loom-file release=0.15.56 revision=4 policy=package-priority
// LOOM v0.15.56 — Canonical user cleanup + legacy-orphan client sweeping.
declare(strict_types=1);

function loom_cleanup_bool(array $o,string $k,bool $default=true): bool { return array_key_exists($k,$o)?(bool)$o[$k]:$default; }
function loom_cleanup_set(array $values): array { $out=[];foreach($values as $v){$v=safe_token((string)$v);if($v!=='')$out[$v]=true;}return $out; }
function loom_cleanup_ids(array $set): array { return array_keys($set); }
function loom_cleanup_matches(array $set,?string $id): bool { $id=safe_token((string)$id);return $id!==''&&isset($set[$id]); }
function loom_cleanup_write_json(string $file,array $data): void { ensure_dir(dirname($file));$json=json_encode($data,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT);if($json===false||@file_put_contents($file,$json."\n",LOCK_EX)===false)throw new RuntimeException('Could not update '.basename($file).'.'); }
function loom_cleanup_all_user_ids(): array {
  $ids=[];foreach((loom_temp_account_store()['users']??[]) as $uid=>$u){$id=safe_token((string)($u['userId']??$u['user_id']??$uid));if($id!=='')$ids[$id]=true;}
  if(loom_db_ready())try{$q=loom_db_pdo(true)->query("SELECT user_id FROM loom_users");foreach($q->fetchAll() as $r){$id=safe_token((string)$r['user_id']);if($id!=='')$ids[$id]=true;}}catch(Throwable $e){}
  return array_keys($ids);
}
function loom_cleanup_all_guest_ids(): array { $ids=[];foreach((loom_guest_store()['guests']??[]) as $gid=>$g){$id=safe_token((string)($g['guestId']??$gid));if($id!=='')$ids[$id]=true;}if(loom_db_ready())try{$q=loom_db_pdo(true)->query("SELECT guest_id FROM loom_guest_identities");foreach($q->fetchAll() as $r){$id=safe_token((string)$r['guest_id']);if($id!=='')$ids[$id]=true;}}catch(Throwable $e){}return array_keys($ids); }
function loom_cleanup_all_client_ids(): array {
  $ids=[];$add=function($v)use(&$ids){$v=safe_token((string)$v);if($v!==''&&str_starts_with($v,'client_'))$ids[$v]=true;};
  if(function_exists('loom_guest_discover_existing_client_ids'))foreach(loom_guest_discover_existing_client_ids() as $cid)$add($cid);
  $a=loom_temp_account_store();foreach(array_keys((array)($a['clients']??[])) as $cid)$add($cid);
  $gs=loom_guest_store();foreach(array_keys((array)($gs['clientMap']??[])) as $cid)$add($cid);foreach((array)($gs['guests']??[]) as $g)foreach(array_keys((array)($g['clients']??[])) as $cid)$add($cid);
  $gps=loom_guest_profiles_store();foreach(array_keys((array)($gps['clientProfileMap']??[])) as $cid)$add($cid);foreach((array)($gps['profiles']??[]) as $p)foreach((array)($p['generations']??[]) as $g)$add($g['clientId']??'');
  if(function_exists('loom_continuity_read_store')){ $c=loom_continuity_read_store();foreach(array_keys((array)($c['clients']??[])) as $cid)$add($cid); }
  if(loom_db_ready())try{$pdo=loom_db_pdo(true);foreach([
    "SELECT client_id AS cid FROM loom_clients","SELECT client_id AS cid FROM loom_client_profiles","SELECT client_id AS cid FROM loom_user_clients","SELECT client_id AS cid FROM loom_guest_clients",
    "SELECT owner_id AS cid FROM loom_global_profiles WHERE owner_type='client'","SELECT owner_id AS cid FROM loom_project_identities WHERE owner_type='client'","SELECT owner_id AS cid FROM loom_project_module_state WHERE owner_type='client'","SELECT owner_id AS cid FROM loom_identity_ips WHERE owner_type='client'"
  ] as $sql)try{foreach($pdo->query($sql) as $r)$add($r['cid']??'');}catch(Throwable $ignored){}}catch(Throwable $e){}
  return array_keys($ids);
}
function loom_cleanup_user_linked_client_ids(): array {
  $ids=[];$a=loom_temp_account_store();foreach((array)($a['clients']??[]) as $cid=>$uid)if(safe_token((string)$uid)!=='')$ids[safe_token((string)$cid)]=true;
  if(loom_db_ready())try{foreach(loom_db_pdo(true)->query("SELECT client_id FROM loom_user_clients") as $r){$cid=safe_token((string)$r['client_id']);if($cid!=='')$ids[$cid]=true;}foreach(loom_db_pdo(true)->query("SELECT client_id FROM loom_clients WHERE user_id IS NOT NULL AND user_id<>''") as $r){$cid=safe_token((string)$r['client_id']);if($cid!=='')$ids[$cid]=true;}}catch(Throwable $e){}
  return $ids;
}
function loom_cleanup_guest_wrapped_client_ids(): array {
  $ids=[];$gs=loom_guest_store();foreach(array_keys((array)($gs['clientMap']??[])) as $cid){$cid=safe_token((string)$cid);if($cid!=='')$ids[$cid]=true;}foreach((array)($gs['guests']??[]) as $g)foreach(array_keys((array)($g['clients']??[])) as $cid){$cid=safe_token((string)$cid);if($cid!=='')$ids[$cid]=true;}
  if(loom_db_ready())try{foreach(loom_db_pdo(true)->query("SELECT client_id FROM loom_guest_clients") as $r){$cid=safe_token((string)$r['client_id']);if($cid!=='')$ids[$cid]=true;}}catch(Throwable $e){}
  return $ids;
}
function loom_cleanup_orphan_client_ids(bool $includeOwner=false): array {
  $linked=loom_cleanup_user_linked_client_ids();$wrapped=loom_cleanup_guest_wrapped_client_ids();$owner=safe_token(loom_access_system_owner_client_id());$out=[];
  foreach(loom_cleanup_all_client_ids() as $cid){$cid=safe_token($cid);if($cid===''||isset($linked[$cid])||isset($wrapped[$cid]))continue;if(!$includeOwner&&$owner!==''&&hash_equals($owner,$cid))continue;$out[$cid]=true;}
  return array_keys($out);
}
function loom_cleanup_db_values(string $sql,array $params=[]): array { if(!loom_db_ready())return [];try{$st=loom_db_pdo(true)->prepare($sql);$st->execute($params);return array_values(array_filter(array_map(fn($v)=>safe_token((string)$v),$st->fetchAll(PDO::FETCH_COLUMN)),fn($v)=>$v!==''));}catch(Throwable $e){return [];} }
function loom_cleanup_plan(string $kind,string $subjectId,array $options=[]): array {
  $allowed=['user-one','guest-one','users-all','guests-all','orphans-all','all-except-owner','factory-all'];if(!in_array($kind,$allowed,true))throw new RuntimeException('Choose a valid cleanup target.');
  $subjectId=safe_token($subjectId);$ownerUser=loom_access_system_owner_user_id();$ownerClient=loom_access_system_owner_client_id();$users=[];$guests=[];
  if($kind==='user-one'){if($subjectId==='')throw new RuntimeException('Choose a permanent account.');if($ownerUser!==''&&hash_equals($ownerUser,$subjectId))throw new RuntimeException('The System Owner can only be removed with the explicit Factory identity wipe target.');$users[$subjectId]=true;}
  elseif($kind==='guest-one'){if($subjectId==='')throw new RuntimeException('Choose a Guest Identity.');$guests[$subjectId]=true;}
  elseif($kind==='users-all'){foreach(loom_cleanup_all_user_ids() as $uid)if($ownerUser===''||!hash_equals($ownerUser,$uid))$users[$uid]=true;}
  elseif($kind==='guests-all'){foreach(loom_cleanup_all_guest_ids() as $gid)$guests[$gid]=true;}
  elseif($kind==='orphans-all'){}
  elseif($kind==='all-except-owner'){foreach(loom_cleanup_all_user_ids() as $uid)if($ownerUser===''||!hash_equals($ownerUser,$uid))$users[$uid]=true;foreach(loom_cleanup_all_guest_ids() as $gid)$guests[$gid]=true;}
  elseif($kind==='factory-all'){foreach(loom_cleanup_all_user_ids() as $uid)$users[$uid]=true;foreach(loom_cleanup_all_guest_ids() as $gid)$guests[$gid]=true;}

  $guestStore=loom_guest_store();if(loom_cleanup_bool($options,'attachedGuests',false)&&$users){foreach(($guestStore['guests']??[]) as $gid=>$g)if(loom_cleanup_matches($users,(string)($g['attachedUserId']??'')))$guests[safe_token((string)($g['guestId']??$gid))]=true;foreach(loom_cleanup_db_values("SELECT guest_id FROM loom_guest_identities WHERE attached_user_id IN (".implode(',',array_fill(0,count($users),'?')).")",array_keys($users)) as $gid)$guests[$gid]=true;}

  $clients=[];$profiles=[];$installations=[];$orphanClients=[];
  if(in_array($kind,['guests-all','orphans-all','all-except-owner','factory-all'],true)){foreach(loom_cleanup_orphan_client_ids($kind==='factory-all') as $cid){$clients[$cid]=true;$orphanClients[$cid]=true;}}
  foreach(($guestStore['guests']??[]) as $gid=>$g){$id=safe_token((string)($g['guestId']??$gid));if(!isset($guests[$id]))continue;$pc=safe_token((string)($g['primaryClientId']??''));if($pc!=='')$clients[$pc]=true;foreach(array_keys((array)($g['clients']??[])) as $cid){$cid=safe_token((string)$cid);if($cid!=='')$clients[$cid]=true;}}
  // Browser clients linked to a deleted permanent account are intentionally not
  // treated as deleted guest clients unless Attached Guest Histories is selected.
  // Removing an account detaches those links; preserved Guest Histories keep their
  // client-owned project state, continuity evidence and presentation data.
  if($guests){$ph=implode(',',array_fill(0,count($guests),'?'));foreach(loom_cleanup_db_values("SELECT client_id FROM loom_guest_clients WHERE guest_id IN ($ph)",array_keys($guests)) as $cid)$clients[$cid]=true;}
  $gps=loom_guest_profiles_store();foreach(($gps['profiles']??[]) as $pid=>$p){$hit=false;foreach((array)($p['generations']??[]) as $g){if(loom_cleanup_matches($guests,(string)($g['guestId']??''))||loom_cleanup_matches($clients,(string)($g['clientId']??''))){$hit=true;break;}}if($hit)$profiles[safe_token((string)($p['guestProfileId']??$pid))]=true;}
  foreach(($gps['installationMap']??[]) as $iid=>$pids)foreach((array)$pids as $pid)if(isset($profiles[safe_token((string)$pid)])){$iid=safe_token((string)$iid);if($iid!=='')$installations[$iid]=true;}
  if($guests||$clients){$conds=[];$params=[];if($guests){$conds[]='guest_id IN ('.implode(',',array_fill(0,count($guests),'?')).')';$params=array_merge($params,array_keys($guests));}if($clients){$conds[]='client_id IN ('.implode(',',array_fill(0,count($clients),'?')).')';$params=array_merge($params,array_keys($clients));}if($conds)foreach(loom_cleanup_db_values("SELECT DISTINCT guest_profile_id FROM loom_guest_profile_generations WHERE ".implode(' OR ',$conds),$params) as $pid)$profiles[$pid]=true;}

  $flags=['projectData'=>loom_cleanup_bool($options,'projectData',true),'activity'=>loom_cleanup_bool($options,'activity',true),'referrals'=>loom_cleanup_bool($options,'referrals',true),'continuity'=>loom_cleanup_bool($options,'continuity',true),'media'=>loom_cleanup_bool($options,'media',true),'audit'=>loom_cleanup_bool($options,'audit',false),'attachedGuests'=>loom_cleanup_bool($options,'attachedGuests',false)];
  $scope=(string)($options['scope']??'both');if(!in_array($scope,['local','database','both'],true))$scope='both';
  $phrase=$kind==='factory-all'?'WIPE ALL IDENTITIES AND OWNER':(in_array($kind,['users-all','guests-all','orphans-all','all-except-owner'],true)?'DELETE ALL SELECTED IDENTITIES':'DELETE IDENTITY DATA');
  $warnings=[];if($orphanClients)$warnings[]=count($orphanClients).' legacy orphan client record(s) have no canonical Guest Identity or permanent-account owner and will be swept.';if(in_array($scope,['database','both'],true)&&!loom_db_ready())$warnings[]='Database cleanup was selected, but SQL is not currently connected; execution will stop instead of silently skipping it.';if($scope==='database')$warnings[]='Database-only deletion leaves the durable local fallback files intact; a future migration could restore them. Use Both for a complete deletion.';if($kind==='factory-all'){$warnings[]='Factory identity wipe removes the System Owner record and returns LOOM to first-run Admin bootstrap state.';if(loom_db_ready()&&$scope!=='both')$warnings[]='Because SQL is connected, Factory identity wipe requires Durable local + SQL together so the System Owner cannot survive in the other persistence layer.';}if(!$flags['audit'])$warnings[]='Audit history is preserved by default for accountability and may still contain historical identity IDs.';
  return ['kind'=>$kind,'subjectId'=>$subjectId?:null,'scope'=>$scope,'flags'=>$flags,'systemOwner'=>['userId'=>$ownerUser?:null,'clientId'=>$ownerClient?:null],'userIds'=>array_keys($users),'guestIds'=>array_keys($guests),'clientIds'=>array_keys($clients),'guestProfileIds'=>array_keys($profiles),'installationIds'=>array_keys($installations),'orphanClientIds'=>array_keys($orphanClients),'counts'=>['permanentUsers'=>count($users),'guestIdentities'=>count($guests),'browserClients'=>count($clients),'orphanClients'=>count($orphanClients),'guestProfiles'=>count($profiles),'installations'=>count($installations)],'confirmPhrase'=>$phrase,'warnings'=>$warnings];
}
function loom_cleanup_contains_ids(mixed $v,array $sets): bool { if(is_array($v)){foreach($v as $x)if(loom_cleanup_contains_ids($x,$sets))return true;return false;}$s=safe_token((string)$v);if($s==='')return false;foreach($sets as $set)if(isset($set[$s]))return true;return false; }
function loom_cleanup_filter_jsonl(string $file,array $sets): int { if(!is_file($file))return 0;$kept=[];$removed=0;foreach(@file($file,FILE_IGNORE_NEW_LINES)?:[] as $line){if(trim($line)==='')continue;$r=json_decode($line,true);if(is_array($r)&&loom_cleanup_contains_ids($r,$sets)){$removed++;continue;}$kept[]=$line;}if($removed)@file_put_contents($file,$kept?implode("\n",$kept)."\n":'',LOCK_EX);return $removed; }
function loom_cleanup_delete_media_for(string $type,string $id): int { $id=safe_token($id);if($id==='')return 0;$n=0;$hash=hash('sha256',$id);foreach([loom_avatar_root().'/users',loom_avatar_root().'/clients',loom_avatar_root().'/global-profiles'] as $dir)foreach(glob($dir.'/*'.$hash.'*')?:[] as $f)if(is_file($f)&&@unlink($f))$n++;foreach(glob(loom_avatar_project_root().'/*/*'.$hash.'*')?:[] as $f)if(is_file($f)&&@unlink($f))$n++;return $n; }
function loom_cleanup_local(array $plan): array {
  $users=loom_cleanup_set($plan['userIds']);$guests=loom_cleanup_set($plan['guestIds']);$clients=loom_cleanup_set($plan['clientIds']);$profiles=loom_cleanup_set($plan['guestProfileIds']);$installs=loom_cleanup_set($plan['installationIds']);$f=$plan['flags'];$counts=['records'=>0,'files'=>0,'activityRows'=>0];
  // Permanent accounts, auth sessions and username reservations.
  $a=loom_temp_account_store();foreach(array_keys($users) as $uid)if(isset($a['users'][$uid])){unset($a['users'][$uid]);$counts['records']++;}foreach(($a['clients']??[]) as $cid=>$uid)if(isset($users[safe_token((string)$uid)])){unset($a['clients'][$cid]);$counts['records']++;}foreach(($a['sessions']??[]) as $k=>$r)if(loom_cleanup_matches($users,(string)($r['userId']??''))||loom_cleanup_matches($clients,(string)($r['clientId']??''))){unset($a['sessions'][$k]);$counts['records']++;}foreach(($a['usernames']??[]) as $k=>$r){$t=(string)($r['ownerType']??'');$id=safe_token((string)($r['ownerId']??''));if(($t==='user'&&isset($users[$id]))||($t==='client'&&isset($clients[$id]))){unset($a['usernames'][$k]);$counts['records']++;}}loom_write_temp_account_store($a);
  // Guest identity provenance. User deletion detaches surviving guests; explicit guest deletion removes them.
  $gs=loom_guest_store();foreach(($gs['guests']??[]) as $gid=>$g){$id=safe_token((string)($g['guestId']??$gid));if(isset($guests[$id])){unset($gs['guests'][$gid]);$counts['records']++;continue;}if(loom_cleanup_matches($users,(string)($g['attachedUserId']??''))){$g['attachedUserId']=null;$g['attachedAt']=null;if(($g['status']??'')==='attached')$g['status']='unattached';$g['updatedAt']=server_timestamp();$gs['guests'][$gid]=$g;}}
  foreach(($gs['clientMap']??[]) as $cid=>$gid)if(isset($guests[safe_token((string)$gid)])||isset($clients[safe_token((string)$cid)])&&isset($guests[safe_token((string)($gs['clientMap'][$cid]??''))]))unset($gs['clientMap'][$cid]);
  foreach(($gs['attachments']??[]) as $k=>$r)if(loom_cleanup_matches($guests,(string)($r['guestId']??''))||loom_cleanup_matches($users,(string)($r['userId']??''))){unset($gs['attachments'][$k]);$counts['records']++;}
  foreach(($gs['recoveryIndex']??[]) as $k=>$gid)if(isset($guests[safe_token((string)$gid)]))unset($gs['recoveryIndex'][$k]);
  foreach(($gs['conflicts']??[]) as $k=>$r)if(loom_cleanup_matches($guests,(string)($r['guestId']??''))||loom_cleanup_matches($users,(string)($r['userId']??''))){unset($gs['conflicts'][$k]);$counts['records']++;}
  loom_guest_write_store($gs);foreach(array_keys($guests) as $gid){$d=loom_identity_dir().'/guest-snapshots/'.$gid;if(is_dir($d)){recursive_remove($d);$counts['files']++;}$d=loom_identity_dir().'/guest-assets/'.$gid;if(is_dir($d)){recursive_remove($d);$counts['files']++;}}
  // Guest profiles/generations.
  $ps=loom_guest_profiles_store();foreach(($ps['profiles']??[]) as $pid=>$p){$clean=safe_token((string)($p['guestProfileId']??$pid));if(isset($profiles[$clean])){unset($ps['profiles'][$pid]);$counts['records']++;continue;}if(loom_cleanup_matches($users,(string)($p['lastClaimedUserId']??'')))$p['lastClaimedUserId']=null;foreach((array)($p['generations']??[]) as $gk=>$g)if(loom_cleanup_matches($users,(string)($g['userId']??''))){$g['userId']=null;if(($g['status']??'')==='claimed')$g['status']='active';$p['generations'][$gk]=$g;}$ps['profiles'][$pid]=$p;}
  foreach(($ps['clientProfileMap']??[]) as $cid=>$pid)if(isset($profiles[safe_token((string)$pid)]))unset($ps['clientProfileMap'][$cid]);foreach(($ps['installationMap']??[]) as $iid=>$pids){$ps['installationMap'][$iid]=array_values(array_filter((array)$pids,fn($pid)=>!isset($profiles[safe_token((string)$pid)])));if(!$ps['installationMap'][$iid])unset($ps['installationMap'][$iid]);}$ps['schemaVersion']='2.0';$ps['updatedAt']=server_timestamp();loom_cleanup_write_json(loom_guest_profiles_file(),$ps);
  // Global profiles.
  $gp=loom_global_profile_store();foreach(($gp['profiles']??[]) as $k=>$r){$t=(string)($r['ownerType']??$r['owner_type']??'');$id=safe_token((string)($r['ownerId']??$r['owner_id']??''));if(($t==='user'&&isset($users[$id]))||($t==='client'&&isset($clients[$id]))){unset($gp['profiles'][$k]);$counts['records']++;}}loom_write_global_profile_store($gp);
  // Canonical LOOM/global + project moderation belongs to the person, not a browser client.
  $m=loom_moderation_store();foreach(array_keys((array)($m['identityStates']??[])) as $key){$r=(array)$m['identityStates'][$key];$t=(string)($r['subjectType']??'');$id=safe_token((string)($r['subjectId']??''));if(($t==='user'&&isset($users[$id]))||($t==='guest'&&isset($guests[$id]))){unset($m['identityStates'][$key]);$counts['records']++;}}loom_write_moderation_store($m);
  // Raw client-profile files are independent legacy records and can outlive a Guest Identity wrapper.
  // Remove them only when the client is not still linked to a surviving permanent account.
  foreach(array_keys($clients) as $cid){$linked=loom_account_user_for_client($cid);$uid=safe_token((string)($linked['user_id']??$linked['userId']??''));if($uid!==''&&!isset($users[$uid]))continue;$file=loom_data_dir().'/users/'.hash('sha256',$cid).'.json';if(is_file($file)&&@unlink($file))$counts['files']++;}
  // Project-owned identity/state and delegated access.
  if($f['projectData']){
    $pi=loom_project_identity_store();foreach(($pi['identities']??[]) as $k=>$r){$t=(string)($r['ownerType']??$r['owner_type']??'');$id=safe_token((string)($r['ownerId']??$r['owner_id']??''));if(($t==='user'&&isset($users[$id]))||($t==='client'&&isset($clients[$id]))){unset($pi['identities'][$k]);$counts['records']++;}}loom_write_project_identity_store($pi);
    foreach(glob(loom_project_state_dir().'/*.json')?:[] as $file){$s=read_json_file($file)?:[];$before=count($s);foreach(array_keys($s) as $k){foreach($users as $uid=>$_)if(str_ends_with((string)$k,'|user|'.$uid)){unset($s[$k]);continue 2;}foreach($clients as $cid=>$_)if(str_ends_with((string)$k,'|client|'.$cid)){unset($s[$k]);continue 2;}}if(count($s)!==$before){loom_cleanup_write_json($file,$s);$counts['records']+=$before-count($s);}}
    $m=loom_moderation_store();foreach(($m['projectStates']??[]) as $project=>$rows){foreach(array_keys((array)$rows) as $key){[$t,$id]=array_pad(explode(':',(string)$key,2),2,'');if(($t==='user'&&isset($users[$id]))||($t==='client'&&isset($clients[$id])))unset($m['projectStates'][$project][$key]);}if(empty($m['projectStates'][$project]))unset($m['projectStates'][$project]);}loom_write_moderation_store($m);
    $ac=loom_access_store();foreach(array_keys($users) as $uid)unset($ac['loomAdmins'][$uid]);foreach(($ac['projectGrants']??[]) as $project=>$rows){foreach(array_keys((array)$rows) as $key){[$t,$id]=array_pad(explode(':',(string)$key,2),2,'');if(($t==='user'&&isset($users[$id]))||($t==='guest'&&isset($profiles[$id]))||($t==='client'&&isset($clients[$id])))unset($ac['projectGrants'][$project][$key]);}if(empty($ac['projectGrants'][$project]))unset($ac['projectGrants'][$project]);}loom_access_write($ac);
  }
  if($f['continuity']){
    $n=loom_network_store();foreach(array_keys($users) as $id)unset($n['identities']['user:'.$id]);foreach(array_keys($clients) as $id)unset($n['identities']['client:'.$id]);loom_write_network_store($n);
    $c=loom_continuity_read_store();foreach(array_keys($clients) as $cid)unset($c['clients'][$cid],$c['pendingLocks'][$cid]);foreach(array_keys($guests) as $gid)unset($c['guestLocks'][$gid]);foreach(($c['clusters']??[]) as $ck=>$row){$row['guestIds']=array_values(array_filter((array)($row['guestIds']??[]),fn($x)=>!isset($guests[safe_token((string)$x)])));$row['clientIds']=array_values(array_filter((array)($row['clientIds']??[]),fn($x)=>!isset($clients[safe_token((string)$x)])));$row['profileIds']=array_values(array_filter((array)($row['profileIds']??[]),fn($x)=>!isset($profiles[safe_token((string)$x)])));$row['installationIds']=array_values(array_filter((array)($row['installationIds']??[]),fn($x)=>!isset($installs[safe_token((string)$x)])));if(loom_cleanup_matches($users,(string)($row['claimedUserId']??''))){$row['claimedUserId']=null;$row['claimedAt']=null;}if(!$row['guestIds']&&!$row['clientIds'])unset($c['clusters'][$ck]);else $c['clusters'][$ck]=$row;}foreach(['installationLocks','decisions','ambiguityEvents'] as $bucket)foreach(($c[$bucket]??[]) as $k=>$row)if(loom_cleanup_contains_ids($row,[$users,$guests,$clients,$profiles,$installs]))unset($c[$bucket][$k]);loom_cleanup_write_json(loom_continuity_file(),$c);
  }
  if($f['referrals']){$r=loom_referral_read_store();foreach(($r['shares']??[]) as $code=>$row){$a=(array)($row['referrer']??[]);if(loom_cleanup_matches($users,(string)($a['userId']??''))||loom_cleanup_matches($guests,(string)($a['guestId']??''))||loom_cleanup_matches($clients,(string)($a['clientId']??'')))unset($r['shares'][$code]);}foreach(($r['acceptances']??[]) as $k=>$row){$drop=false;foreach(['referrer','visitor'] as $side){$a=(array)($row[$side]??[]);if(loom_cleanup_matches($users,(string)($a['userId']??''))||loom_cleanup_matches($guests,(string)($a['guestId']??''))||loom_cleanup_matches($clients,(string)($a['clientId']??'')))$drop=true;}if($drop)unset($r['acceptances'][$k]);}foreach(($r['shares']??[]) as $code=>$row){$cnt=0;foreach(($r['acceptances']??[]) as $a)if(($a['shareCode']??'')===$code)$cnt++;$r['shares'][$code]['referrals']=$cnt;}loom_cleanup_write_json(loom_referral_file(),$r);}
  if($f['media']){foreach(array_keys($users) as $id)$counts['files']+=loom_cleanup_delete_media_for('user',$id);foreach(array_keys($clients) as $id)$counts['files']+=loom_cleanup_delete_media_for('client',$id);}
  if($f['activity']){foreach(glob(loom_data_dir().'/logs/*/*.jsonl')?:[] as $file)$counts['activityRows']+=loom_cleanup_filter_jsonl($file,[$users,$clients,$profiles]);foreach(glob(loom_data_dir().'/replay/*/*.jsonl')?:[] as $file)$counts['activityRows']+=loom_cleanup_filter_jsonl($file,[$users,$clients,$profiles]);foreach(glob(loom_data_dir().'/presence/*/*.json')?:[] as $file){$r=read_json_file($file);if(is_array($r)&&loom_cleanup_contains_ids($r,[$users,$clients,$profiles])){@unlink($file);$counts['files']++;}}}
  if($f['audit']){foreach(glob(loom_audit_dir().'/*.jsonl')?:[] as $file)$counts['activityRows']+=loom_cleanup_filter_jsonl($file,[$users,$guests,$clients,$profiles]);$counts['activityRows']+=loom_cleanup_filter_jsonl(loom_identity_audit_file(),[$users,$guests,$clients,$profiles]);$m=loom_moderation_store();$m['audit']=array_values(array_filter((array)($m['audit']??[]),fn($r)=>!loom_cleanup_contains_ids($r,[$users,$guests,$clients,$profiles])));loom_write_moderation_store($m);}
  // Password-reset tokens are core account data, not optional audit history.
  if(function_exists('loom_email_reset_store')){$e=loom_email_reset_store();foreach(($e['tokens']??[]) as $k=>$r)if(loom_cleanup_matches($users,(string)($r['userId']??'')))unset($e['tokens'][$k]);loom_email_write_reset_store($e);}
  if($plan['kind']==='factory-all'){@unlink(loom_admin_identity_file());@unlink(loom_access_file());$GLOBALS['loom_access_request_cache']=null;}
  return $counts;
}
function loom_cleanup_sql_in(string $column,array $ids,array &$params): string { if(!$ids)return '1=0';$params=array_merge($params,$ids);return $column.' IN ('.implode(',',array_fill(0,count($ids),'?')).')'; }
function loom_cleanup_db_exec(PDO $pdo,string $sql,array $params,array &$summary,string $label): void { try{$st=$pdo->prepare($sql);$st->execute($params);$summary['rows']+=(int)$st->rowCount();$summary['steps'][]=['label'=>$label,'rows'=>(int)$st->rowCount()];}catch(Throwable $e){$summary['skipped'][]=['label'=>$label,'reason'=>$e->getMessage()];} }
function loom_cleanup_database(array $plan): array {
  if(!loom_db_ready())throw new RuntimeException('SQL cleanup was requested, but the LOOM database is not connected.');$pdo=loom_db_pdo(true);if(!$pdo)throw new RuntimeException('Database connection unavailable.');$users=array_values($plan['userIds']);$guests=array_values($plan['guestIds']);$clients=array_values($plan['clientIds']);$profiles=array_values($plan['guestProfileIds']);$f=$plan['flags'];$s=['rows'=>0,'steps'=>[],'skipped'=>[]];
  $pdo->beginTransaction();try{
    if($plan['kind']==='factory-all')loom_cleanup_db_exec($pdo,"DELETE FROM loom_admin_state",[],$s,'system owner state');
    if($f['activity']){foreach([['loom_sessions','user_id','client_id'],['loom_events','user_id','client_id'],['loom_interaction_events','user_id','client_id']] as [$table,$uc,$cc]){$parts=[];$params=[];if($users)$parts[]=loom_cleanup_sql_in($uc,$users,$params);if($clients)$parts[]=loom_cleanup_sql_in($cc,$clients,$params);if($parts)loom_cleanup_db_exec($pdo,"DELETE FROM $table WHERE ".implode(' OR ',$parts),$params,$s,$table.' activity');}}
    if($f['audit']){$parts=[];$params=[];if($users)$parts[]=loom_cleanup_sql_in('user_id',$users,$params);if($clients)$parts[]=loom_cleanup_sql_in('client_id',$clients,$params);if($profiles)$parts[]=loom_cleanup_sql_in('guest_profile_id',$profiles,$params);if($parts)loom_cleanup_db_exec($pdo,"DELETE FROM loom_audit_events WHERE ".implode(' OR ',$parts),$params,$s,'audit events');$parts=[];$params=[];if($users){$parts[]=loom_cleanup_sql_in('admin_user_id',$users,$params);$parts[]=loom_cleanup_sql_in('target_id',$users,$params);}if($clients)$parts[]=loom_cleanup_sql_in('admin_client_id',$clients,$params);if($parts)loom_cleanup_db_exec($pdo,"DELETE FROM loom_admin_audit WHERE ".implode(' OR ',$parts),$params,$s,'admin audit');}
    $modParts=[];$modParams=[];if($users){$modParams[]='user';$modParams=array_merge($modParams,$users);$modParts[]='(subject_type=? AND subject_id IN ('.implode(',',array_fill(0,count($users),'?')).'))';}if($guests){$modParams[]='guest';$modParams=array_merge($modParams,$guests);$modParts[]='(subject_type=? AND subject_id IN ('.implode(',',array_fill(0,count($guests),'?')).'))';}if($modParts)loom_cleanup_db_exec($pdo,"DELETE FROM loom_identity_moderation WHERE ".implode(' OR ',$modParts),$modParams,$s,'canonical moderation');
    if($f['projectData']){foreach([['loom_project_module_state','owner_type','owner_id'],['loom_project_identities','owner_type','owner_id'],['loom_project_user_state','subject_type','subject_id']] as [$table,$tc,$ic]){$parts=[];$params=[];if($users){$params[]='user';$params=array_merge($params,$users);$parts[]="($tc=? AND $ic IN (".implode(',',array_fill(0,count($users),'?'))."))";}if($clients){$params[]='client';$params=array_merge($params,$clients);$parts[]="($tc=? AND $ic IN (".implode(',',array_fill(0,count($clients),'?'))."))";}if($parts)loom_cleanup_db_exec($pdo,"DELETE FROM $table WHERE ".implode(' OR ',$parts),$params,$s,$table);}}
    if($f['continuity']){foreach([['user',$users],['client',$clients]] as [$type,$ids])if($ids){$params=[$type];$cond=loom_cleanup_sql_in('owner_id',$ids,$params);loom_cleanup_db_exec($pdo,"DELETE FROM loom_identity_ips WHERE owner_type=? AND $cond",$params,$s,'network identity history');}}
    if($profiles){$params=[];$cond=loom_cleanup_sql_in('guest_profile_id',$profiles,$params);loom_cleanup_db_exec($pdo,"DELETE FROM loom_guest_profile_installations WHERE $cond",$params,$s,'guest profile installations');loom_cleanup_db_exec($pdo,"DELETE FROM loom_guest_profile_generations WHERE $cond",$params,$s,'guest profile generations');loom_cleanup_db_exec($pdo,"DELETE FROM loom_guest_profiles WHERE $cond",$params,$s,'guest profiles');}
    elseif($users){$params=[];$cond=loom_cleanup_sql_in('user_id',$users,$params);loom_cleanup_db_exec($pdo,"UPDATE loom_guest_profile_generations SET user_id=NULL,status=IF(status='claimed','active',status),claimed_at=NULL WHERE $cond",$params,$s,'detach guest generations');$params=[];$cond=loom_cleanup_sql_in('last_claimed_user_id',$users,$params);loom_cleanup_db_exec($pdo,"UPDATE loom_guest_profiles SET last_claimed_user_id=NULL WHERE $cond",$params,$s,'detach guest profiles');}
    if($guests){$params=[];$cond=loom_cleanup_sql_in('guest_id',$guests,$params);foreach(['loom_guest_recovery','loom_identity_attachments','loom_identity_merge_conflicts','loom_guest_clients','loom_guest_identities'] as $table)loom_cleanup_db_exec($pdo,"DELETE FROM $table WHERE $cond",$params,$s,$table);}
    elseif($users){$params=[];$cond=loom_cleanup_sql_in('user_id',$users,$params);loom_cleanup_db_exec($pdo,"DELETE FROM loom_identity_attachments WHERE $cond",$params,$s,'identity attachments');loom_cleanup_db_exec($pdo,"DELETE FROM loom_identity_merge_conflicts WHERE $cond",$params,$s,'identity merge conflicts');$params=[];$cond=loom_cleanup_sql_in('attached_user_id',$users,$params);loom_cleanup_db_exec($pdo,"UPDATE loom_guest_identities SET attached_user_id=NULL,attached_at=NULL,status=IF(status='attached','unattached',status) WHERE $cond",$params,$s,'detach surviving guests');}
    foreach([['user',$users],['client',$clients]] as [$type,$ids])if($ids){$params=[$type];$cond=loom_cleanup_sql_in('owner_id',$ids,$params);loom_cleanup_db_exec($pdo,"DELETE FROM loom_global_profiles WHERE owner_type=? AND $cond",$params,$s,'global profiles');loom_cleanup_db_exec($pdo,"DELETE FROM loom_username_registry WHERE owner_type=? AND $cond",$params,$s,'username registry');}
    if($users){$params=[];$cond=loom_cleanup_sql_in('user_id',$users,$params);loom_cleanup_db_exec($pdo,"DELETE FROM loom_auth_sessions WHERE $cond",$params,$s,'auth sessions');loom_cleanup_db_exec($pdo,"DELETE FROM loom_user_avatar_profiles WHERE $cond",$params,$s,'avatar metadata');loom_cleanup_db_exec($pdo,"DELETE FROM loom_user_clients WHERE $cond",$params,$s,'user/client links');loom_cleanup_db_exec($pdo,"UPDATE loom_clients SET user_id=NULL WHERE $cond",$params,$s,'client account links');loom_cleanup_db_exec($pdo,"DELETE FROM loom_users WHERE $cond",$params,$s,'permanent accounts');}
    if($clients){$params=[];$cond=loom_cleanup_sql_in('c.client_id',$clients,$params);loom_cleanup_db_exec($pdo,"DELETE c FROM loom_client_profiles c LEFT JOIN loom_user_clients u ON u.client_id=c.client_id LEFT JOIN loom_clients lc ON lc.client_id=c.client_id WHERE $cond AND u.client_id IS NULL AND (lc.user_id IS NULL OR lc.user_id='')",$params,$s,'orphan guest client profiles');$params=[];$cond=loom_cleanup_sql_in('c.client_id',$clients,$params);loom_cleanup_db_exec($pdo,"DELETE c FROM loom_clients c LEFT JOIN loom_user_clients u ON u.client_id=c.client_id WHERE $cond AND u.client_id IS NULL AND (c.user_id IS NULL OR c.user_id='')",$params,$s,'orphan guest clients');}
    $pdo->commit();return $s;
  }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
}
function loom_identity_cleanup_preview(string $kind,string $subjectId,array $options=[]): array { $p=loom_cleanup_plan($kind,$subjectId,$options);return ['ok'=>true,'plan'=>$p,'databaseReady'=>loom_db_ready(),'message'=>'Preview only. Nothing has been deleted.']; }
function loom_identity_cleanup_execute(string $kind,string $subjectId,array $options,string $confirmPhrase): array {
  $p=loom_cleanup_plan($kind,$subjectId,$options);if($kind==='factory-all'&&loom_db_ready()&&$p['scope']!=='both')throw new RuntimeException('Factory identity wipe requires Durable local + SQL together while a database is connected.');if(!hash_equals((string)$p['confirmPhrase'],trim($confirmPhrase)))throw new RuntimeException('Confirmation phrase did not match. Preview again and type the exact phrase shown.');if(in_array($p['scope'],['database','both'],true)&&!loom_db_ready())throw new RuntimeException('SQL cleanup was selected, but the database is not connected. Nothing was deleted.');
  $result=['local'=>null,'database'=>null];if(in_array($p['scope'],['local','both'],true))$result['local']=loom_cleanup_local($p);if(in_array($p['scope'],['database','both'],true))$result['database']=loom_cleanup_database($p);
  if($kind!=='factory-all')loom_admin_audit('identity.permanent-delete','identity',$subjectId,'',['kind'=>$kind,'scope'=>$p['scope'],'counts'=>$p['counts'],'flags'=>$p['flags']]);
  return ['ok'=>true,'deleted'=>true,'plan'=>$p,'result'=>$result,'ownerReset'=>$kind==='factory-all','message'=>$kind==='factory-all'?'Identity factory wipe complete. LOOM has returned to first-run Admin ownership state.':'Permanent identity deletion completed.'];
}
