<?php
// @loom-file release=0.12.11 revision=2 policy=package-priority
declare(strict_types=1);
function loom_migration_ledger_file(): string { ensure_dir(loom_data_dir().'/migrations');return loom_data_dir().'/migrations/ledger.json'; }
function loom_migration_definitions(): array { return [
 ['id'=>'01208-guest-profile-lineage','version'=>'0.12.08','description'=>'Add explicit guest profiles and generation lineage.'],
 ['id'=>'01208-capability-contracts','version'=>'0.12.08','description'=>'Add module capability contracts and scoped token foundation.'],
 ['id'=>'01208-audit-causality','version'=>'0.12.08','description'=>'Add human-readable audit/correlation foundation.'],
 ['id'=>'01208-session-replay-foundation','version'=>'0.12.08','description'=>'Add masked interaction replay event storage.'],
 ['id'=>'01208-health-schema','version'=>'0.12.08','description'=>'Add health/failure-state surfaces.'],
 ['id'=>'01208-foundation-db-mirrors','version'=>'0.12.08','description'=>'Create additive SQL mirrors for guest lineage, audit, and replay foundation.']
]; }
function loom_migration_ledger(): array { return array_replace(['schemaVersion'=>'1.0','migrations'=>[]],read_json_file(loom_migration_ledger_file())?:[]); }
function loom_migration_write(array $s): void {$s['updatedAt']=server_timestamp();@file_put_contents(loom_migration_ledger_file(),json_encode($s,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT),LOCK_EX);}
function loom_migration_tables(): void { if(!loom_db_ready())return;try{$pdo=loom_db_pdo(true);$sql=[
 "CREATE TABLE IF NOT EXISTS loom_schema_migrations (migration_id VARCHAR(128) PRIMARY KEY,version VARCHAR(32) NOT NULL,status VARCHAR(32) NOT NULL,description VARCHAR(255) NULL,applied_at DATETIME(3) NULL,verified_at DATETIME(3) NULL,details_json LONGTEXT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS loom_guest_profiles (guest_profile_id VARCHAR(96) PRIMARY KEY,display_name VARCHAR(64) NOT NULL,avatar_preset VARCHAR(32) NOT NULL,current_generation INT UNSIGNED NOT NULL DEFAULT 1,last_claimed_user_id VARCHAR(96) NULL,created_at DATETIME(3) NULL,updated_at DATETIME(3) NULL,payload_json LONGTEXT NULL,INDEX idx_guest_profile_updated(updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS loom_guest_profile_generations (guest_profile_id VARCHAR(96) NOT NULL,generation INT UNSIGNED NOT NULL,client_id VARCHAR(96) NOT NULL,guest_id VARCHAR(96) NULL,status VARCHAR(32) NOT NULL,user_id VARCHAR(96) NULL,created_at DATETIME(3) NULL,claimed_at DATETIME(3) NULL,PRIMARY KEY(guest_profile_id,generation),UNIQUE KEY uq_guest_generation_client(client_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS loom_guest_profile_installations (installation_id VARCHAR(128) NOT NULL,guest_profile_id VARCHAR(96) NOT NULL,linked_at DATETIME(3) NOT NULL,PRIMARY KEY(installation_id,guest_profile_id),INDEX idx_guest_install_profile(guest_profile_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS loom_interaction_events (replay_id VARCHAR(96) PRIMARY KEY,project_slug VARCHAR(96) NOT NULL,session_id VARCHAR(96) NOT NULL,client_id VARCHAR(96) NOT NULL,user_id VARCHAR(96) NULL,event_type VARCHAR(48) NOT NULL,server_timestamp DATETIME(3) NOT NULL,payload_json LONGTEXT NULL,INDEX idx_replay_session(session_id,server_timestamp),INDEX idx_replay_project(project_slug,server_timestamp)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
 "CREATE TABLE IF NOT EXISTS loom_audit_events (audit_id VARCHAR(96) PRIMARY KEY,event_type VARCHAR(96) NOT NULL,message_text VARCHAR(512) NULL,client_id VARCHAR(96) NULL,user_id VARCHAR(96) NULL,guest_profile_id VARCHAR(96) NULL,project_slug VARCHAR(96) NULL,cause_id VARCHAR(96) NULL,correlation_id VARCHAR(96) NULL,created_at DATETIME(3) NOT NULL,details_json LONGTEXT NULL,INDEX idx_audit_project(project_slug,created_at),INDEX idx_audit_actor(user_id,created_at),INDEX idx_audit_corr(correlation_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
 ];foreach($sql as $q)$pdo->exec($q);}catch(Throwable $e){} }
function loom_migration_bootstrap(): array { static $done=null;if($done!==null)return $done;$s=loom_migration_ledger();$defs=loom_migration_definitions();$dbReady=loom_db_ready();$pending=[];foreach($defs as $def){$row=$s['migrations'][$def['id']]??null;if(!is_array($row)||($row['status']??'')!=='applied'||($dbReady&&empty($row['dbApplied'])))$pending[]=$def;}if(!$pending)return $done=$s;if($dbReady)loom_migration_tables();foreach($pending as $def){$id=$def['id'];$existing=$s['migrations'][$id]??[];$now=server_timestamp();$row=['id'=>$id,'version'=>$def['version'],'description'=>$def['description'],'status'=>'applied','appliedAt'=>$existing['appliedAt']??$now,'verifiedAt'=>$now,'mode'=>'additive-idempotent','dbApplied'=>$dbReady?true:(bool)($existing['dbApplied']??false)];$s['migrations'][$id]=$row;if($dbReady)try{$st=loom_db_pdo(true)->prepare("INSERT INTO loom_schema_migrations(migration_id,version,status,description,applied_at,verified_at,details_json) VALUES(?,?, 'applied',?,UTC_TIMESTAMP(3),UTC_TIMESTAMP(3),?) ON DUPLICATE KEY UPDATE status='applied',verified_at=VALUES(verified_at),description=VALUES(description),details_json=VALUES(details_json)");$st->execute([$id,$def['version'],$def['description'],json_encode(['mode'=>'additive-idempotent','dbApplied'=>true])]);}catch(Throwable $e){$s['migrations'][$id]['dbApplied']=false;}}loom_migration_write($s);return $done=$s; }
