<?php
// @loom-file release=0.15.60 revision=1 policy=package-priority
declare(strict_types=1);
function loom_project_release_updates_root(): string { return root_dir().'/project-updates'; }
function loom_project_release_update_state_file(string $project): string { $d=loom_data_dir().'/project-updates';ensure_dir($d);return $d.'/'.safe_slug($project).'.json'; }
function loom_project_release_updates_for(string $project): array { $dir=loom_project_release_updates_root().'/'.safe_slug($project);if(!is_dir($dir))return [];$out=[];foreach(glob($dir.'/*/update.json')?:[] as $f){$m=read_json_file($f);if(is_array($m)&&($m['project']??'')===safe_slug($project))$out[]=['manifest'=>$m,'sourceDir'=>dirname($f)];}usort($out,fn($a,$b)=>version_compare((string)($a['manifest']['release']??'0'),(string)($b['manifest']['release']??'0')));return $out; }
function loom_project_release_atomic_copy(string $src,string $dest): void { ensure_dir(dirname($dest));$tmp=$dest.'.loom-update-'.bin2hex(random_bytes(4)).'.tmp';if(!@copy($src,$tmp))throw new RuntimeException('Could not stage project update file.');@chmod($tmp,0664);if(!@rename($tmp,$dest)){@unlink($tmp);throw new RuntimeException('Could not commit project update file.');} }
function loom_apply_project_release_updates(string $project): array {
  $project=safe_slug($project);$projectContent=project_dir($project);$base=$projectContent?dirname($projectContent):null;if($project===''||!$base||!is_dir($base))return ['ok'=>true,'applied'=>[],'conflicts'=>[]];$state=read_json_file(loom_project_release_update_state_file($project))?:['schemaVersion'=>'1.0','updates'=>[]];$applied=[];$conflicts=[];
  foreach(loom_project_release_updates_for($project) as $pack){$m=$pack['manifest'];$id=safe_token((string)($m['updateId']??''));if($id===''||(($state['updates'][$id]['status']??'')==='applied'))continue;$backupRoot=loom_instance_root().'/backups/project-updates/'.gmdate('Ymd-His').'-'.$project.'-'.$id;$planned=[];$bad=[];
    foreach(($m['files']??[]) as $f){$rel=ltrim(str_replace('\\','/',(string)($f['path']??'')),'/');if($rel===''||str_contains($rel,'..')){$bad[]=['path'=>$rel,'reason'=>'invalid-path'];continue;}$src=$pack['sourceDir'].'/'.$rel;$dest=$base.'/'.$rel;if(!is_file($src)){$bad[]=['path'=>$rel,'reason'=>'missing-payload'];continue;}$want=strtolower((string)($f['sha256']??''));if($want===''||!hash_equals($want,hash_file('sha256',$src)?:'')){$bad[]=['path'=>$rel,'reason'=>'payload-hash-mismatch'];continue;}$current=is_file($dest)?(hash_file('sha256',$dest)?:''):'';if($current!==''&&hash_equals($want,$current))continue;$allowed=array_map('strtolower',array_values((array)($f['allowedPreviousSha256']??[])));if($current!==''&&!in_array(strtolower($current),$allowed,true)){$bad[]=['path'=>$rel,'reason'=>'local-project-drift','currentSha256'=>$current];continue;}$planned[]=['rel'=>$rel,'src'=>$src,'dest'=>$dest];}
    if($bad){$state['updates'][$id]=['status'=>'conflict','release'=>$m['release']??null,'checkedAt'=>server_timestamp(),'conflicts'=>$bad];$conflicts=array_merge($conflicts,array_map(fn($x)=>['updateId'=>$id]+$x,$bad));continue;}
    $written=[];try{foreach($planned as $x){$had=is_file($x['dest']);if($had){$b=$backupRoot.'/'.$x['rel'];ensure_dir(dirname($b));if(!@copy($x['dest'],$b))throw new RuntimeException('Could not back up project update target.');}$written[]=['rel'=>$x['rel'],'dest'=>$x['dest'],'had'=>$had];loom_project_release_atomic_copy($x['src'],$x['dest']);}}
    catch(Throwable $e){for($i=count($written)-1;$i>=0;$i--){$w=$written[$i];$b=$backupRoot.'/'.$w['rel'];if($w['had']&&is_file($b)){@copy($b,$w['dest']);}elseif(!$w['had']&&is_file($w['dest'])){@unlink($w['dest']);}}$fail=['path'=>'*','reason'=>'apply-failed','message'=>$e->getMessage()];$state['updates'][$id]=['status'=>'failed','release'=>$m['release']??null,'checkedAt'=>server_timestamp(),'conflicts'=>[$fail]];$conflicts[]=['updateId'=>$id]+$fail;continue;}
    $state['updates'][$id]=['status'=>'applied','release'=>$m['release']??null,'appliedAt'=>server_timestamp(),'fileCount'=>count($planned),'backupRoot'=>is_dir($backupRoot)?str_replace(root_dir().'/','',$backupRoot):null];$applied[]=$id;if(function_exists('loom_identity_audit'))loom_identity_audit('project.release-update.applied',['project'=>$project,'updateId'=>$id,'release'=>$m['release']??null,'fileCount'=>count($planned)]);
  }
  $state['updatedAt']=server_timestamp();@file_put_contents(loom_project_release_update_state_file($project),json_encode($state,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT),LOCK_EX);return ['ok'=>!$conflicts,'applied'=>$applied,'conflicts'=>$conflicts];
}
