<?php
// @loom-file release=0.15.62 revision=3 policy=package-priority
// LOOM v0.15.61 — Single-user portability graph, export/import helpers.
declare(strict_types=1);

const LOOM_USER_PORTABLE_FORMAT='loom-user-portable/v1';

function loom_user_portability_set_add(array &$set,string $value): bool {
  $value=safe_token($value);if($value==='')return false;$new=!isset($set[$value]);$set[$value]=true;return $new;
}
function loom_user_portability_set(array $values): array { $s=[];foreach($values as $v)loom_user_portability_set_add($s,(string)$v);return $s; }
function loom_user_portability_ids(array $set): array { return array_keys($set); }
function loom_user_portability_has(array $set,?string $value): bool { $v=safe_token((string)$value);return $v!==''&&isset($set[$v]); }
function loom_user_portability_account_normalize(array $u): array {
  $uid=safe_token((string)($u['user_id']??$u['userId']??''));
  return [
    'userId'=>$uid,
    'username'=>(string)($u['username']??''),
    'usernameNorm'=>(string)($u['username_norm']??$u['usernameNorm']??loom_username_norm((string)($u['username']??''))),
    'email'=>(string)($u['email']??''),
    'emailNorm'=>(string)($u['email_norm']??$u['emailNorm']??loom_email_norm((string)($u['email']??''))),
    'passwordHash'=>(string)($u['password_hash']??$u['passwordHash']??''),
    'privilege'=>(string)($u['privilege']??'User'),
    'createdAt'=>(string)($u['created_at']??$u['createdAt']??server_timestamp()),
    'updatedAt'=>(string)($u['updated_at']??$u['updatedAt']??server_timestamp()),
  ];
}
function loom_user_portability_display_name(string $userId): string {
  $p=loom_global_profile_get('user',$userId);if(is_array($p)){$n=function_exists('loom_global_profile_display_name')?loom_global_profile_display_name($p):loom_clean_username((string)($p['displayName']??$p['username']??''));if($n!=='')return $n;}
  $u=loom_account_user_by_id($userId);$name=loom_clean_username((string)($u['username']??''));return $name!==''?$name:$userId;
}
function loom_user_portability_all_users(string $clientId): array {
  loom_backup_require_owner($clientId);$out=[];
  foreach(loom_cleanup_all_user_ids() as $uid){$uid=safe_token($uid);if($uid==='')continue;$u=loom_account_user_by_id($uid);if(!is_array($u))continue;$a=loom_user_portability_account_normalize($u);$projects=[];foreach(loom_project_identity_list_for_owner('user',$uid) as $r){$p=safe_slug((string)($r['project']??''));if($p!=='')$projects[$p]=true;}foreach(loom_project_state_rows_for_owner('user',$uid) as $r){$p=safe_slug((string)($r['project']??''));if($p!=='')$projects[$p]=true;}
    $out[]=['userId'=>$uid,'displayName'=>loom_user_portability_display_name($uid),'email'=>$a['email'],'accountHandle'=>$a['username'],'privilege'=>$a['privilege'],'projectCount'=>count($projects),'isSystemOwner'=>$uid===loom_access_system_owner_user_id()];
  }
  usort($out,fn($a,$b)=>strcasecmp((string)$a['displayName'],(string)$b['displayName']));return $out;
}
function loom_user_portability_db_values(string $sql,array $params=[]): array {
  if(!loom_db_ready())return [];try{$st=loom_db_pdo(true)->prepare($sql);$st->execute($params);return $st->fetchAll(PDO::FETCH_ASSOC)?:[];}catch(Throwable $e){return [];}
}
function loom_user_portability_graph(string $userId): array {
  $userId=safe_token($userId);$u=loom_account_user_by_id($userId);if($userId===''||!is_array($u))throw new RuntimeException('User account not found.');
  $users=[$userId=>true];$clients=[];$guests=[];$profiles=[];$installs=[];
  $a=loom_temp_account_store();foreach((array)($a['clients']??[]) as $cid=>$uid)if(safe_token((string)$uid)===$userId)loom_user_portability_set_add($clients,(string)$cid);
  if(loom_db_ready()){
    foreach(loom_user_portability_db_values("SELECT client_id FROM loom_user_clients WHERE user_id=?",[$userId]) as $r)loom_user_portability_set_add($clients,(string)($r['client_id']??''));
    foreach(loom_user_portability_db_values("SELECT client_id FROM loom_clients WHERE user_id=?",[$userId]) as $r)loom_user_portability_set_add($clients,(string)($r['client_id']??''));
    foreach(loom_user_portability_db_values("SELECT guest_id FROM loom_guest_identities WHERE attached_user_id=?",[$userId]) as $r)loom_user_portability_set_add($guests,(string)($r['guest_id']??''));
    foreach(loom_user_portability_db_values("SELECT guest_id,source_client_id FROM loom_identity_attachments WHERE user_id=?",[$userId]) as $r){loom_user_portability_set_add($guests,(string)($r['guest_id']??''));loom_user_portability_set_add($clients,(string)($r['source_client_id']??''));}
  }
  $gs=loom_guest_store();
  // Expand client <-> Guest History ownership to a fixed point. Historical attachment rows count too.
  for($round=0;$round<4;$round++){$changed=false;foreach((array)($gs['guests']??[]) as $gid=>$g){$gid=safe_token((string)($g['guestId']??$gid));$hit=loom_user_portability_has($guests,$gid)||safe_token((string)($g['attachedUserId']??''))===$userId||loom_user_portability_has($clients,(string)($g['primaryClientId']??''));if(!$hit)foreach(array_keys((array)($g['clients']??[])) as $cid)if(loom_user_portability_has($clients,(string)$cid)){$hit=true;break;}if(!$hit)continue;if(loom_user_portability_set_add($guests,$gid))$changed=true;if(loom_user_portability_set_add($clients,(string)($g['primaryClientId']??'')))$changed=true;foreach(array_keys((array)($g['clients']??[])) as $cid)if(loom_user_portability_set_add($clients,(string)$cid))$changed=true;}
    if(loom_db_ready()&&$clients){$ids=array_keys($clients);$ph=implode(',',array_fill(0,count($ids),'?'));foreach(loom_user_portability_db_values("SELECT client_id,guest_id FROM loom_guest_clients WHERE client_id IN ($ph)",$ids) as $r){if(loom_user_portability_set_add($clients,(string)$r['client_id']))$changed=true;if(loom_user_portability_set_add($guests,(string)$r['guest_id']))$changed=true;}}
    if(loom_db_ready()&&$guests){$ids=array_keys($guests);$ph=implode(',',array_fill(0,count($ids),'?'));foreach(loom_user_portability_db_values("SELECT client_id,guest_id FROM loom_guest_clients WHERE guest_id IN ($ph)",$ids) as $r){if(loom_user_portability_set_add($clients,(string)$r['client_id']))$changed=true;if(loom_user_portability_set_add($guests,(string)$r['guest_id']))$changed=true;}}
    if(!$changed)break;
  }
  $gps=loom_guest_profiles_store();foreach((array)($gps['profiles']??[]) as $pid=>$p){$pid=safe_token((string)($p['guestProfileId']??$pid));$hit=safe_token((string)($p['lastClaimedUserId']??''))===$userId;foreach((array)($p['generations']??[]) as $g){if(safe_token((string)($g['userId']??''))===$userId||loom_user_portability_has($clients,(string)($g['clientId']??''))||loom_user_portability_has($guests,(string)($g['guestId']??''))){$hit=true;loom_user_portability_set_add($clients,(string)($g['clientId']??''));loom_user_portability_set_add($guests,(string)($g['guestId']??''));}}if($hit)loom_user_portability_set_add($profiles,$pid);}
  if(loom_db_ready()){
    foreach(loom_user_portability_db_values("SELECT DISTINCT guest_profile_id,client_id,guest_id FROM loom_guest_profile_generations WHERE user_id=?",[$userId]) as $r){loom_user_portability_set_add($profiles,(string)$r['guest_profile_id']);loom_user_portability_set_add($clients,(string)$r['client_id']);loom_user_portability_set_add($guests,(string)$r['guest_id']);}
    if($clients||$guests){$parts=[];$params=[];if($clients){$ids=array_keys($clients);$parts[]='client_id IN ('.implode(',',array_fill(0,count($ids),'?')).')';$params=array_merge($params,$ids);}if($guests){$ids=array_keys($guests);$parts[]='guest_id IN ('.implode(',',array_fill(0,count($ids),'?')).')';$params=array_merge($params,$ids);}foreach(loom_user_portability_db_values("SELECT DISTINCT guest_profile_id,client_id,guest_id FROM loom_guest_profile_generations WHERE ".implode(' OR ',$parts),$params) as $r){loom_user_portability_set_add($profiles,(string)$r['guest_profile_id']);loom_user_portability_set_add($clients,(string)$r['client_id']);loom_user_portability_set_add($guests,(string)$r['guest_id']);}}
    foreach(loom_user_portability_db_values("SELECT guest_profile_id FROM loom_guest_profiles WHERE last_claimed_user_id=?",[$userId]) as $r)loom_user_portability_set_add($profiles,(string)$r['guest_profile_id']);
  }
  foreach((array)($gps['installationMap']??[]) as $iid=>$pids)foreach((array)$pids as $pid)if(loom_user_portability_has($profiles,(string)$pid)){loom_user_portability_set_add($installs,(string)$iid);break;}
  if(loom_db_ready()&&$profiles){$ids=array_keys($profiles);$ph=implode(',',array_fill(0,count($ids),'?'));foreach(loom_user_portability_db_values("SELECT DISTINCT installation_id FROM loom_guest_profile_installations WHERE guest_profile_id IN ($ph)",$ids) as $r)loom_user_portability_set_add($installs,(string)$r['installation_id']);}
  return ['userIds'=>[$userId],'clientIds'=>array_keys($clients),'guestIds'=>array_keys($guests),'guestProfileIds'=>array_keys($profiles),'installationIds'=>array_keys($installs)];
}
function loom_user_portability_sets(array $graph): array { return [loom_user_portability_set($graph['userIds']??[]),loom_user_portability_set($graph['guestIds']??[]),loom_user_portability_set($graph['clientIds']??[]),loom_user_portability_set($graph['guestProfileIds']??[]),loom_user_portability_set($graph['installationIds']??[])]; }
function loom_user_portability_contains(mixed $v,array $sets): bool { return loom_cleanup_contains_ids($v,$sets); }
function loom_user_portability_recursive_remap(mixed $v,array $maps): mixed {
  if(is_array($v)){$out=[];foreach($v as $k=>$x){$nk=is_string($k)?loom_user_portability_remap_key($k,$maps):$k;$out[$nk]=loom_user_portability_recursive_remap($x,$maps);}return $out;}
  if(!is_string($v))return $v;foreach($maps as $map)if(isset($map[$v]))return $map[$v];return $v;
}
function loom_user_portability_remap_key(string $key,array $maps): string {
  if(str_contains($key,'|')){$parts=explode('|',$key);foreach($parts as &$p)foreach($maps as $m)if(isset($m[$p])){$p=$m[$p];break;}unset($p);return implode('|',$parts);}if(str_contains($key,':')){$parts=explode(':',$key);foreach($parts as &$p)foreach($maps as $m)if(isset($m[$p])){$p=$m[$p];break;}unset($p);return implode(':',$parts);}foreach($maps as $m)if(isset($m[$key]))return $m[$key];return $key;
}
function loom_user_portability_local_capture(array $graph): array {
  [$users,$guests,$clients,$profiles,$installs]=loom_user_portability_sets($graph);$uid=(string)($graph['userIds'][0]??'');
  $a=loom_temp_account_store();$accounts=['user'=>$a['users'][$uid]??null,'clients'=>[],'usernames'=>[]];foreach((array)($a['clients']??[]) as $cid=>$u)if(isset($clients[safe_token((string)$cid)])&&safe_token((string)$u)===$uid)$accounts['clients'][$cid]=$u;foreach((array)($a['usernames']??[]) as $k=>$r){$t=(string)($r['ownerType']??'');$id=safe_token((string)($r['ownerId']??''));if(($t==='user'&&isset($users[$id]))||($t==='client'&&isset($clients[$id])))$accounts['usernames'][$k]=$r;}
  $clientProfiles=[];foreach(array_keys($clients) as $cid){$file=loom_data_dir().'/users/'.hash('sha256',$cid).'.json';$r=read_json_file($file);if(is_array($r))$clientProfiles[$cid]=$r;}
  $gp=[];foreach((loom_global_profile_store()['profiles']??[]) as $k=>$r){$t=(string)($r['ownerType']??$r['owner_type']??'');$id=safe_token((string)($r['ownerId']??$r['owner_id']??''));if(($t==='user'&&isset($users[$id]))||($t==='client'&&isset($clients[$id])))$gp[$k]=$r;}
  $pi=[];foreach((loom_project_identity_store()['identities']??[]) as $k=>$r){$t=(string)($r['ownerType']??$r['owner_type']??'');$id=safe_token((string)($r['ownerId']??$r['owner_id']??''));if(($t==='user'&&isset($users[$id]))||($t==='client'&&isset($clients[$id])))$pi[$k]=$r;}
  $state=[];foreach(glob(loom_project_state_dir().'/*.json')?:[] as $file){$project=basename($file,'.json');foreach((read_json_file($file)?:[]) as $k=>$r){foreach(array_keys($users) as $id)if(str_ends_with((string)$k,'|user|'.$id)){$state[$project][$k]=$r;continue 2;}foreach(array_keys($clients) as $id)if(str_ends_with((string)$k,'|client|'.$id)){$state[$project][$k]=$r;continue 2;}}}
  $gs=loom_guest_store();$guestSlice=['guests'=>[],'clientMap'=>[],'attachments'=>[],'conflicts'=>[]];foreach((array)($gs['guests']??[]) as $gid=>$r)if(isset($guests[safe_token((string)($r['guestId']??$gid))])){$copy=$r;$copy['recoveryHash']=null;$guestSlice['guests'][$gid]=$copy;}foreach((array)($gs['clientMap']??[]) as $cid=>$gid)if(isset($clients[safe_token((string)$cid)])||isset($guests[safe_token((string)$gid)]))$guestSlice['clientMap'][$cid]=$gid;foreach((array)($gs['attachments']??[]) as $k=>$r)if(loom_user_portability_contains($r,[$users,$guests,$clients,$profiles]))$guestSlice['attachments'][$k]=$r;foreach((array)($gs['conflicts']??[]) as $k=>$r)if(loom_user_portability_contains($r,[$users,$guests,$clients,$profiles]))$guestSlice['conflicts'][$k]=$r;
  $gps=loom_guest_profiles_store();$guestProfiles=['profiles'=>[],'installationMap'=>[],'clientProfileMap'=>[]];foreach((array)($gps['profiles']??[]) as $pid=>$r)if(isset($profiles[safe_token((string)($r['guestProfileId']??$pid))]))$guestProfiles['profiles'][$pid]=$r;foreach((array)($gps['installationMap']??[]) as $iid=>$pids)if(isset($installs[safe_token((string)$iid)]))$guestProfiles['installationMap'][$iid]=array_values(array_filter((array)$pids,fn($pid)=>isset($profiles[safe_token((string)$pid)])));foreach((array)($gps['clientProfileMap']??[]) as $cid=>$pid)if(isset($clients[safe_token((string)$cid)])||isset($profiles[safe_token((string)$pid)]))$guestProfiles['clientProfileMap'][$cid]=$pid;
  $moderation=loom_moderation_store();$mod=['identityStates'=>[],'projectStates'=>[],'audit'=>[]];foreach((array)($moderation['identityStates']??[]) as $k=>$r)if(loom_user_portability_contains($r,[$users,$guests,$clients,$profiles]))$mod['identityStates'][$k]=$r;foreach((array)($moderation['projectStates']??[]) as $project=>$rows)foreach((array)$rows as $k=>$r)if(loom_user_portability_contains([$k,$r],[$users,$guests,$clients,$profiles]))$mod['projectStates'][$project][$k]=$r;foreach((array)($moderation['audit']??[]) as $r)if(loom_user_portability_contains($r,[$users,$guests,$clients,$profiles]))$mod['audit'][]=$r;
  $access=loom_access_store();$accessSlice=['loomAdmin'=>$access['loomAdmins'][$uid]??null,'projectGrants'=>[]];foreach((array)($access['projectGrants']??[]) as $project=>$rows)foreach((array)$rows as $k=>$r)if(loom_user_portability_contains([$k,$r],[$users,$guests,$clients,$profiles]))$accessSlice['projectGrants'][$project][$k]=$r;
  $network=loom_network_store();$networkSlice=['identities'=>[]];foreach((array)($network['identities']??[]) as $k=>$r)if(loom_user_portability_contains([$k,$r],[$users,$clients]))$networkSlice['identities'][$k]=$r;
  $continuity=loom_continuity_read_store();$continuitySlice=[];foreach(['clients','pendingLocks'] as $bucket){foreach((array)($continuity[$bucket]??[]) as $k=>$r)if(isset($clients[safe_token((string)$k)])||loom_user_portability_contains($r,[$users,$guests,$clients,$profiles,$installs]))$continuitySlice[$bucket][$k]=$r;}foreach(['guestLocks'] as $bucket)foreach((array)($continuity[$bucket]??[]) as $k=>$r)if(isset($guests[safe_token((string)$k)])||loom_user_portability_contains($r,[$users,$guests,$clients,$profiles,$installs]))$continuitySlice[$bucket][$k]=$r;foreach(['clusters','installationLocks','decisions','ambiguityEvents'] as $bucket)foreach((array)($continuity[$bucket]??[]) as $k=>$r)if(loom_user_portability_contains([$k,$r],[$users,$guests,$clients,$profiles,$installs]))$continuitySlice[$bucket][$k]=$r;
  $refs=loom_referral_read_store();$refSlice=['shares'=>[],'acceptances'=>[]];foreach((array)($refs['shares']??[]) as $k=>$r)if(loom_user_portability_contains($r,[$users,$guests,$clients,$profiles]))$refSlice['shares'][$k]=$r;foreach((array)($refs['acceptances']??[]) as $k=>$r)if(loom_user_portability_contains($r,[$users,$guests,$clients,$profiles]))$refSlice['acceptances'][$k]=$r;
  return ['accounts'=>$accounts,'clientProfiles'=>$clientProfiles,'globalProfiles'=>$gp,'projectIdentities'=>$pi,'projectState'=>$state,'guestIdentity'=>$guestSlice,'guestProfiles'=>$guestProfiles,'moderation'=>$mod,'access'=>$accessSlice,'network'=>$networkSlice,'continuity'=>$continuitySlice,'referrals'=>$refSlice];
}
function loom_user_portability_db_table_rows(string $table,array $graph): array {
  if(!loom_db_ready())return [];[$users,$guests,$clients,$profiles,$installs]=loom_user_portability_sets($graph);$uid=(string)($graph['userIds'][0]??'');$pdo=loom_db_pdo(true);if(!$pdo)return [];
  $excluded=['loom_auth_sessions','loom_guest_recovery','loom_admin_state','loom_meta','loom_global_settings','loom_module_settings','loom_schema_migrations'];if(in_array($table,$excluded,true))return [];
  try{$cols=$pdo->query('SHOW COLUMNS FROM `'.str_replace('`','',$table).'`')->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable $e){return [];}$names=array_map(fn($c)=>(string)$c['Field'],$cols);$conds=[];$params=[];
  $addIn=function(string $col,array $set)use(&$conds,&$params,$names){if(!$set||!in_array($col,$names,true))return;$ids=array_keys($set);$conds[]='`'.$col.'` IN ('.implode(',',array_fill(0,count($ids),'?')).')';$params=array_merge($params,$ids);};
  foreach(['user_id','attached_user_id','last_claimed_user_id'] as $c)$addIn($c,$users);foreach(['client_id','source_client_id','primary_client_id'] as $c)$addIn($c,$clients);foreach(['guest_id','merged_into_guest_id'] as $c)$addIn($c,$guests);$addIn('guest_profile_id',$profiles);$addIn('installation_id',$installs);
  if(in_array('owner_type',$names,true)&&in_array('owner_id',$names,true)){if($users){$ids=array_keys($users);$conds[]="(`owner_type`='user' AND `owner_id` IN (".implode(',',array_fill(0,count($ids),'?')).'))';$params=array_merge($params,$ids);}if($clients){$ids=array_keys($clients);$conds[]="(`owner_type`='client' AND `owner_id` IN (".implode(',',array_fill(0,count($ids),'?')).'))';$params=array_merge($params,$ids);}}
  if(in_array('subject_type',$names,true)&&in_array('subject_id',$names,true)){if($users){$ids=array_keys($users);$conds[]="(`subject_type`='user' AND `subject_id` IN (".implode(',',array_fill(0,count($ids),'?')).'))';$params=array_merge($params,$ids);}foreach([$guests,$profiles] as $set)if($set){$ids=array_keys($set);$conds[]="(`subject_type`='guest' AND `subject_id` IN (".implode(',',array_fill(0,count($ids),'?')).'))';$params=array_merge($params,$ids);}}
  // Audit/history tables are allowed to include rows where this person was the actor/target.
  if(in_array($table,['loom_admin_audit','loom_audit_events'],true)){foreach(['admin_user_id','target_id'] as $c)$addIn($c,$users);$addIn('admin_client_id',$clients);}
  if($table==='loom_identity_audit'&&in_array('payload_json',$names,true)){foreach(array_merge(array_keys($users),array_keys($guests),array_keys($clients),array_keys($profiles)) as $id){$conds[]='`payload_json` LIKE ?';$params[]='%'.str_replace(['%','_'],['\\%','\\_'],$id).'%';}}
  if(!$conds)return [];try{$st=$pdo->prepare('SELECT * FROM `'.str_replace('`','',$table).'` WHERE '.implode(' OR ',$conds));$st->execute($params);return $st->fetchAll(PDO::FETCH_ASSOC)?:[];}catch(Throwable $e){return [];}
}
function loom_user_portability_db_capture(array $graph): ?array {
  if(!loom_db_ready())return null;$pdo=loom_db_pdo(true);if(!$pdo)return null;$tables=[];foreach(loom_backup_db_tables($pdo) as $table){$rows=loom_user_portability_db_table_rows($table,$graph);if(!$rows)continue;$cols=[];try{foreach($pdo->query('SHOW COLUMNS FROM `'.str_replace('`','',$table).'`')->fetchAll() as $c)$cols[]=(string)$c['Field'];}catch(Throwable $e){}$tables[$table]=['columns'=>$cols,'rows'=>$rows,'rowCount'=>count($rows)];}
  return ['format'=>'loom-db-portable/v1','driver'=>'mysql','schemaVersion'=>loom_release_version(),'exportedAt'=>server_timestamp(),'excludedTables'=>['loom_auth_sessions','loom_guest_recovery','loom_admin_state'],'authenticationHashesIncluded'=>true,'tables'=>$tables];
}
function loom_user_portability_stream_capture(array $graph): array {
  $sets=loom_user_portability_sets($graph);$files=[];$roots=[loom_data_dir().'/logs'=> 'data/logs',loom_data_dir().'/replay'=>'data/replay',loom_audit_dir()=>'data/audit'];$identityAudit=function_exists('loom_identity_audit_file')?loom_identity_audit_file():'';if($identityAudit&&is_file($identityAudit))$roots[$identityAudit]='data/identity/audit.jsonl';
  foreach($roots as $root=>$label){$list=is_file($root)?[$root]:(is_dir($root)?(glob($root.'/*/*.jsonl')?:[]):[]);if(is_dir($root))$list=array_merge($list,glob($root.'/*.jsonl')?:[]);foreach(array_unique($list) as $file){if(!is_file($file))continue;$rows=[];foreach(@file($file,FILE_IGNORE_NEW_LINES)?:[] as $line){if(trim($line)==='')continue;$r=json_decode($line,true);if(is_array($r)&&loom_user_portability_contains($r,$sets))$rows[]=$r;}if(!$rows)continue;$rel=is_file($root)?$label:rtrim($label,'/').'/'.str_replace('\\','/',substr($file,strlen(rtrim($root,DIRECTORY_SEPARATOR))+1));$files[$rel]=$rows;}}
  return $files;
}
function loom_user_portability_project_refs(array $local,?array $db,array $streams): array {
  $p=[];foreach((array)($local['projectIdentities']??[]) as $r){$s=safe_slug((string)($r['project']??$r['project_slug']??''));if($s!=='')$p[$s]=true;}foreach((array)($local['projectState']??[]) as $s=>$rows){$s=safe_slug((string)$s);if($s!=='')$p[$s]=true;}if(is_array($db))foreach((array)($db['tables']??[]) as $t=>$b)foreach((array)($b['rows']??[]) as $r){$s=safe_slug((string)($r['project_slug']??''));if($s!=='')$p[$s]=true;}foreach(array_keys($streams) as $rel)if(preg_match('#/(?:logs|replay)/([^/]+)/#',$rel,$m)){$s=safe_slug($m[1]);if($s!=='')$p[$s]=true;}return array_keys($p);
}
function loom_user_portability_asset_descriptors(array $graph): array {
  [$users,$guests,$clients]=loom_user_portability_sets($graph);$out=[];$owners=[['user',(string)($graph['userIds'][0]??'')]];foreach(array_keys($clients) as $cid)$owners[]=['client',$cid];foreach($owners as [$type,$id]){
    if($id==='')continue;$f=loom_global_avatar_find($type,$id);if($f)$out[]=['kind'=>'global-avatar','ownerType'=>$type,'ownerId'=>$id,'ext'=>$f['ext'],'source'=>$f['file']];$legacy=loom_avatar_legacy_find_file($type,$id);if($legacy)$out[]=['kind'=>'legacy-avatar','ownerType'=>$type,'ownerId'=>$id,'ext'=>$legacy['ext'],'source'=>$legacy['file']];
    foreach(glob(loom_avatar_project_root().'/*')?:[] as $dir){if(!is_dir($dir))continue;$project=basename($dir);$f=loom_avatar_find_file($project,$type,$id);if($f)$out[]=['kind'=>'project-avatar','project'=>$project,'ownerType'=>$type,'ownerId'=>$id,'ext'=>$f['ext'],'source'=>$f['file']];}
  }
  foreach(array_keys($guests) as $gid)foreach(['guest-snapshots','guest-assets'] as $bucket){$dir=loom_identity_dir().'/'.$bucket.'/'.$gid;if(is_dir($dir))$out[]=['kind'=>$bucket,'guestId'=>$gid,'sourceDir'=>$dir];}
  return $out;
}
function loom_user_portability_capture(string $userId): array {
  $graph=loom_user_portability_graph($userId);$u=loom_account_user_by_id($userId);if(!is_array($u))throw new RuntimeException('User account not found.');$account=loom_user_portability_account_normalize($u);if($account['passwordHash']==='')throw new RuntimeException('The account password hash is unavailable; exact account portability cannot be guaranteed.');$local=loom_user_portability_local_capture($graph);$db=loom_user_portability_db_capture($graph);$streams=loom_user_portability_stream_capture($graph);$projects=loom_user_portability_project_refs($local,$db,$streams);sort($projects);
  return ['format'=>LOOM_USER_PORTABLE_FORMAT,'schemaVersion'=>1,'sourceLoomVersion'=>loom_release_version(),'exportedAt'=>server_timestamp(),'account'=>$account,'displayName'=>loom_user_portability_display_name($userId),'wasSystemOwner'=>$userId===loom_access_system_owner_user_id(),'graph'=>$graph,'projectRefs'=>$projects,'local'=>$local,'database'=>$db,'streams'=>$streams,'security'=>['passwordHashIncluded'=>true,'authSessionsIncluded'=>false,'passwordResetTokensIncluded'=>false,'guestRecoverySecretsIncluded'=>false,'systemOwnerBindingIncluded'=>false]];
}
function loom_user_portability_zip_add_assets(ZipArchive $zip,array $capture,array &$files,array &$assetManifest): void {
  foreach(loom_user_portability_asset_descriptors($capture['graph']) as $a){$kind=(string)$a['kind'];if(isset($a['source'])){$name='payload/user/assets/'.$kind.'/'.safe_token((string)($a['ownerType']??'owner')).'/'.hash('sha256',(string)($a['ownerId']??'')).'.'.preg_replace('/[^a-z0-9]/i','',(string)($a['ext']??'bin'));loom_backup_add_file($zip,(string)$a['source'],$name,$files);$copy=$a;unset($copy['source']);$copy['path']=$name;$assetManifest[]=$copy;continue;}$dir=(string)($a['sourceDir']??'');if(!is_dir($dir))continue;$base=rtrim($dir,DIRECTORY_SEPARATOR);$prefix='payload/user/assets/'.$kind.'/'.safe_token((string)($a['guestId']??'guest'));$it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($base,FilesystemIterator::SKIP_DOTS));$paths=[];foreach($it as $f){if(!$f->isFile())continue;$rel=str_replace('\\','/',substr($f->getPathname(),strlen($base)+1));$dest=$prefix.'/'.$rel;loom_backup_add_file($zip,$f->getPathname(),$dest,$files);$paths[]=$dest;}$copy=$a;unset($copy['sourceDir']);$copy['paths']=$paths;$assetManifest[]=$copy;}
}
function loom_user_portability_preview_payload(array $payload): array {
  if(($payload['format']??'')!==LOOM_USER_PORTABLE_FORMAT)throw new RuntimeException('Unsupported user bundle payload.');$a=(array)($payload['account']??[]);$source=safe_token((string)($a['userId']??''));if($source==='')throw new RuntimeException('User bundle has no canonical user ID.');$existingId=loom_account_user_by_id($source);$existingEmail=($a['email']??'')!==''?loom_account_user_by_email((string)$a['email']):null;$conflicts=[];$target=$source;$mode='exact-create';if(is_array($existingId)){$e=loom_user_portability_account_normalize($existingId);if($e['emailNorm']!==loom_email_norm((string)$a['email']))$conflicts[]='The source user ID already belongs to a different email address on this installation.';else{$mode='exact-merge';$target=$source;}}elseif(is_array($existingEmail)){$e=loom_user_portability_account_normalize($existingEmail);$target=$e['userId'];$mode='email-merge';}
  // Account/global/project usernames and stable identity IDs are ownership-bearing keys.
  $username=loom_clean_username((string)($a['username']??''));if($username!==''){$owner=loom_username_owner($username);if(is_array($owner)){$ot=(string)($owner['owner_type']??$owner['ownerType']??'');$oid=safe_token((string)($owner['owner_id']??$owner['ownerId']??''));if(!($ot==='user'&&in_array($oid,[$source,$target],true)))$conflicts[]='Account handle '.$username.' is already reserved by another identity.';}}
  foreach((array)($payload['local']['globalProfiles']??[]) as $r){$r=(array)$r;$name=loom_clean_username((string)($r['username']??''));if($name==='')continue;$owner=loom_global_profile_username_owner($name);if($owner){$oid=safe_token((string)($owner['ownerId']??''));$ot=(string)($owner['ownerType']??'');if(!($ot==='user'&&in_array($oid,[$source,$target],true)))$conflicts[]='Global profile username '.$name.' is already owned by another identity.';}}
  foreach((array)($payload['local']['projectIdentities']??[]) as $r){$r=(array)$r;$project=safe_slug((string)($r['project']??$r['project_slug']??''));$usernameMode=(string)($r['usernameMode']??$r['username_mode']??'global');$name=loom_clean_username((string)($r['username']??''));if($project===''||$usernameMode!=='project'||$name===''||project_dir($project)===null)continue;try{$other=loom_project_identity_conflict($project,'user',$target,$name);if($other)$conflicts[]='Project username '.$name.' is already in use in '.$project.'.';}catch(Throwable $e){}}
  // Browser client IDs must never be silently stolen from a different permanent user.
  foreach((array)($payload['graph']['clientIds']??[]) as $cid){$linked=loom_account_user_for_client((string)$cid);if(!$linked)continue;$lid=safe_token((string)($linked['user_id']??$linked['userId']??''));if($lid!==''&&$lid!==$target&&$lid!==$source)$conflicts[]='Browser identity '.safe_token((string)$cid).' is already attached to another permanent user.';}
  $guestStore=loom_guest_store();foreach((array)($payload['graph']['guestIds']??[]) as $gid){$gid=safe_token((string)$gid);if($gid==='')continue;$existingGuest=$guestStore['guests'][$gid]??null;if(!is_array($existingGuest))continue;$attached=safe_token((string)($existingGuest['attachedUserId']??''));if($attached!==''&&!in_array($attached,[$source,$target],true))$conflicts[]='Guest History '.$gid.' is already attached to another permanent user.';}
  $profileStore=loom_guest_profiles_store();$sourceClients=loom_user_portability_set((array)($payload['graph']['clientIds']??[]));foreach((array)($payload['graph']['guestProfileIds']??[]) as $pid){$pid=safe_token((string)$pid);if($pid===''||!is_array($profileStore['profiles'][$pid]??null))continue;$ep=(array)$profileStore['profiles'][$pid];$claimed=safe_token((string)($ep['lastClaimedUserId']??''));$same=$claimed!==''&&in_array($claimed,[$source,$target],true);if(!$same)foreach((array)($ep['generations']??[]) as $g)if(isset($sourceClients[safe_token((string)($g['clientId']??''))])){$same=true;break;}if(!$same)$conflicts[]='Guest Profile '.$pid.' already exists for a different identity lineage.';}
  $projects=[];foreach((array)($payload['projectRefs']??[]) as $p){$p=safe_slug((string)$p);if($p==='')continue;$projects[]=['slug'=>$p,'installed'=>project_dir($p)!==null,'dataWillRemainDormantIfMissing'=>project_dir($p)===null];}
  return ['sourceUserId'=>$source,'targetUserId'=>$target,'mode'=>$mode,'displayName'=>$payload['displayName']??$a['username']??$source,'email'=>$a['email']??null,'privilege'=>$a['privilege']??'User','wasSystemOwner'=>(bool)($payload['wasSystemOwner']??false),'graphCounts'=>array_map('count',array_filter((array)($payload['graph']??[]),'is_array')),'projects'=>$projects,'conflicts'=>array_values(array_unique($conflicts)),'canApply'=>empty($conflicts),'samePasswordWillWork'=>!empty($a['passwordHash']),'security'=>$payload['security']??[],'note'=>'System Owner ownership is installation-global and is never transferred by a user bundle. Account privilege and user-owned history are restored.' ];
}
function loom_user_portability_maps(array $payload,string $targetUserId): array { $source=safe_token((string)($payload['account']['userId']??''));$userMap=$source!==''&&$source!==$targetUserId?[$source=>$targetUserId]:[];return [$userMap,[],[],[],[]]; }
function loom_user_portability_db_remap(array $db,array $maps): array { $copy=loom_user_portability_recursive_remap($db,$maps);if(isset($copy['tables']['loom_users']['rows']))foreach($copy['tables']['loom_users']['rows'] as &$r){if(isset($r['user_id'])&&isset($maps[0][$r['user_id']]))$r['user_id']=$maps[0][$r['user_id']];}unset($r);return $copy; }
function loom_user_portability_write_account(array $account,string $targetUserId,array $maps): void {
  $a=loom_user_portability_recursive_remap($account,$maps);$a['userId']=$targetUserId;$a['user_id']=$targetUserId;$row=['userId'=>$targetUserId,'username'=>(string)($a['username']??''),'usernameNorm'=>loom_username_norm((string)($a['username']??'')),'email'=>(string)($a['email']??''),'emailNorm'=>loom_email_norm((string)($a['email']??'')),'passwordHash'=>(string)($a['passwordHash']??$a['password_hash']??''),'privilege'=>(string)($a['privilege']??'User'),'createdAt'=>(string)($a['createdAt']??server_timestamp()),'updatedAt'=>(string)($a['updatedAt']??server_timestamp())];if($row['email']===''||$row['passwordHash']==='')throw new RuntimeException('User bundle account record is incomplete.');$s=loom_temp_account_store();$s['users'][$targetUserId]=$row;loom_write_temp_account_store($s);
}
function loom_user_portability_merge_local(array $payload,string $targetUserId,array $maps): array {
  $local=loom_user_portability_recursive_remap((array)($payload['local']??[]),$maps);loom_user_portability_write_account((array)$payload['account'],$targetUserId,$maps);$counts=['records'=>1,'streams'=>0,'assets'=>0];
  $s=loom_temp_account_store();foreach((array)($local['accounts']['clients']??[]) as $cid=>$uid)$s['clients'][$cid]=$targetUserId;foreach((array)($local['accounts']['usernames']??[]) as $k=>$r){$r=loom_user_portability_recursive_remap($r,$maps);$key=loom_username_norm((string)($r['username']??$k));if($key!=='')$s['usernames'][$key]=$r;}$s['sessions']=is_array($s['sessions']??null)?$s['sessions']:[];loom_write_temp_account_store($s);
  foreach((array)($local['clientProfiles']??[]) as $cid=>$r){$cid=safe_token((string)$cid);if($cid==='')continue;$file=loom_data_dir().'/users/'.hash('sha256',$cid).'.json';$existing=read_json_file($file)?:[];$merged=array_replace_recursive($existing,(array)$r);@file_put_contents($file,json_encode($merged,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT),LOCK_EX);$counts['records']++;}
  $gp=loom_global_profile_store();foreach((array)($local['globalProfiles']??[]) as $k=>$r){$r=(array)$r;$type=(string)($r['ownerType']??$r['owner_type']??'');$id=safe_token((string)($r['ownerId']??$r['owner_id']??''));if($type==='user')$id=$targetUserId;if($id==='')continue;$r['ownerType']=$type;$r['ownerId']=$id;if($type==='user'&&!empty($maps[0]))$r['profileId']=loom_global_profile_id('user',$id);$mode=(string)($r['avatarMode']??$r['avatar_mode']??'');$canonical=loom_global_avatar_preset_normalize($mode);if($canonical!==null)$r['avatarMode']=$canonical;elseif($mode!=='custom')$r['avatarMode']=loom_global_avatar_repair_preset($type,$id);$gp['profiles'][loom_global_profile_key($type,$id)]=$r;$counts['records']++;}loom_write_global_profile_store($gp);
  $pi=loom_project_identity_store();foreach((array)($local['projectIdentities']??[]) as $k=>$r){$r=(array)$r;$project=safe_slug((string)($r['project']??$r['project_slug']??''));$type=(string)($r['ownerType']??$r['owner_type']??'');$id=safe_token((string)($r['ownerId']??$r['owner_id']??''));if($type==='user')$id=$targetUserId;if($project===''||$id==='')continue;$r['project']=$project;$r['ownerType']=$type;$r['ownerId']=$id;if($type==='user'&&!empty($maps[0]))$r['identityId']=loom_project_identity_id($project,'user',$id);if((string)($r['avatarMode']??$r['avatar_mode']??'')==='loom-default')$r['avatarMode']='global';$pi['identities'][loom_project_identity_key($project,$type,$id)]=$r;$counts['records']++;}loom_write_project_identity_store($pi);
  foreach((array)($local['projectState']??[]) as $project=>$rows)foreach((array)$rows as $key=>$r){$parts=explode('|',(string)$key);if(count($parts)<3)continue;$id=array_pop($parts);$type=array_pop($parts);$module=implode('|',$parts);if($type==='user')$id=$targetUserId;loom_project_state_write((string)$project,$module,$type,$id,(array)($r['state']??[]),(string)($r['updatedAt']??server_timestamp()));$counts['records']++;}
  $gs=loom_guest_store();$slice=(array)($local['guestIdentity']??[]);foreach((array)($slice['guests']??[]) as $k=>$r)$gs['guests'][$k]=$r;foreach((array)($slice['clientMap']??[]) as $k=>$v)$gs['clientMap'][$k]=$v;foreach((array)($slice['attachments']??[]) as $k=>$r)$gs['attachments'][$k]=$r;foreach((array)($slice['conflicts']??[]) as $k=>$r)$gs['conflicts'][$k]=$r;loom_guest_write_store($gs);
  $gps=loom_guest_profiles_store();$slice=(array)($local['guestProfiles']??[]);foreach((array)($slice['profiles']??[]) as $k=>$r)$gps['profiles'][$k]=$r;foreach((array)($slice['installationMap']??[]) as $k=>$v)$gps['installationMap'][$k]=array_values(array_unique(array_merge((array)($gps['installationMap'][$k]??[]),(array)$v)));foreach((array)($slice['clientProfileMap']??[]) as $k=>$v)$gps['clientProfileMap'][$k]=$v;loom_guest_profiles_write($gps);
  $m=loom_moderation_store();$slice=(array)($local['moderation']??[]);foreach((array)($slice['identityStates']??[]) as $k=>$r)$m['identityStates'][$k]=$r;foreach((array)($slice['projectStates']??[]) as $project=>$rows)foreach((array)$rows as $k=>$r)$m['projectStates'][$project][$k]=$r;$seen=[];foreach((array)($m['audit']??[]) as $r)$seen[hash('sha256',json_encode($r)?:'')]=true;foreach((array)($slice['audit']??[]) as $r){$h=hash('sha256',json_encode($r)?:'');if(!isset($seen[$h])){$m['audit'][]=$r;$seen[$h]=true;}}loom_write_moderation_store($m);
  $ac=loom_access_store();$slice=(array)($local['access']??[]);if(is_array($slice['loomAdmin']??null))$ac['loomAdmins'][$targetUserId]=$slice['loomAdmin'];foreach((array)($slice['projectGrants']??[]) as $project=>$rows)foreach((array)$rows as $k=>$r)$ac['projectGrants'][$project][$k]=$r;loom_access_write($ac);
  $n=loom_network_store();foreach((array)($local['network']['identities']??[]) as $k=>$r)$n['identities'][$k]=$r;loom_write_network_store($n);
  $c=loom_continuity_read_store();foreach((array)($local['continuity']??[]) as $bucket=>$rows){if(!is_array($rows))continue;if(!isset($c[$bucket])||!is_array($c[$bucket]))$c[$bucket]=[];foreach($rows as $k=>$r)$c[$bucket][$k]=$r;}loom_cleanup_write_json(loom_continuity_file(),$c);
  $rf=loom_referral_read_store();$slice=(array)($local['referrals']??[]);foreach((array)($slice['shares']??[]) as $k=>$r)$rf['shares'][$k]=$r;foreach((array)($slice['acceptances']??[]) as $k=>$r)$rf['acceptances'][$k]=$r;loom_cleanup_write_json(loom_referral_file(),$rf);
  return $counts;
}
function loom_user_portability_append_streams(array $streams): int {$n=0;foreach($streams as $rel=>$rows){$rel=str_replace('\\','/',ltrim((string)$rel,'/'));if(!str_starts_with($rel,'data/'))continue;$target=loom_instance_root().'/'.$rel;ensure_dir(dirname($target));$existing=[];foreach(@file($target,FILE_IGNORE_NEW_LINES)?:[] as $line)if(trim($line)!=='')$existing[hash('sha256',$line)]=true;$add=[];foreach((array)$rows as $r){$line=json_encode($r,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);if($line===false)continue;$h=hash('sha256',$line);if(isset($existing[$h]))continue;$existing[$h]=true;$add[]=$line;$n++;}if($add)@file_put_contents($target,implode("\n",$add)."\n",FILE_APPEND|LOCK_EX);}return $n;}
function loom_user_portability_restore_assets(ZipArchive $zip,array $assets,array $maps): int {$n=0;foreach($assets as $a){$kind=(string)($a['kind']??'');if(isset($a['path'])){$raw=$zip->getFromName((string)$a['path']);if(!is_string($raw))continue;$type=(string)($a['ownerType']??'');$id=safe_token((string)($a['ownerId']??''));if($type==='user'&&isset($maps[0][$id]))$id=$maps[0][$id];$ext=preg_replace('/[^a-z0-9]/i','',(string)($a['ext']??'bin'));if($kind==='global-avatar')$dest=loom_global_avatar_base($type,$id).'.'.$ext;elseif($kind==='legacy-avatar')$dest=loom_avatar_legacy_base_path($type,$id).'.'.$ext;elseif($kind==='project-avatar')$dest=loom_avatar_base_path(safe_slug((string)($a['project']??'')),$type,$id).'.'.$ext;else continue;ensure_dir(dirname($dest));if(@file_put_contents($dest,$raw,LOCK_EX)!==false){@chmod($dest,0664);$n++;}continue;}
    if(in_array($kind,['guest-snapshots','guest-assets'],true)){$gid=safe_token((string)($a['guestId']??''));if($gid==='')continue;$destRoot=loom_identity_dir().'/'.$kind.'/'.$gid;foreach((array)($a['paths']??[]) as $path){$prefix='payload/user/assets/'.$kind.'/'.$gid.'/';if(!str_starts_with((string)$path,$prefix))continue;$rel=substr((string)$path,strlen($prefix));if($rel===''||str_contains($rel,'..'))continue;$raw=$zip->getFromName((string)$path);if(!is_string($raw))continue;$dest=$destRoot.'/'.$rel;ensure_dir(dirname($dest));if(@file_put_contents($dest,$raw,LOCK_EX)!==false){@chmod($dest,0664);$n++;}}}
  }return $n;}
function loom_user_portability_import(ZipArchive $zip,array $payload,array $assetManifest,string $strategy='merge'): array {
  if(($payload['format']??'')!==LOOM_USER_PORTABLE_FORMAT)throw new RuntimeException('Unsupported user bundle.');$preview=loom_user_portability_preview_payload($payload);if(!$preview['canApply'])throw new RuntimeException('User import conflict: '.implode(' ',$preview['conflicts']));if(!in_array($strategy,['merge','create-new'],true))$strategy='merge';if($strategy==='create-new'&&$preview['mode']!=='exact-create')throw new RuntimeException('Create-new import requires a destination with no matching account.');$target=safe_token((string)$preview['targetUserId']);$maps=loom_user_portability_maps($payload,$target);$existing=loom_account_user_by_id($target);$rollback=null;if(is_array($existing))$rollback='user-existing';
  $local=loom_user_portability_merge_local($payload,$target,$maps);$streams=loom_user_portability_append_streams(loom_user_portability_recursive_remap((array)($payload['streams']??[]),$maps));$assets=loom_user_portability_restore_assets($zip,$assetManifest,$maps);$dbResult=null;if(is_array($payload['database']??null)){$db=loom_user_portability_db_remap((array)$payload['database'],$maps);$dbResult=loom_backup_db_apply($db,$strategy==='create-new'?'create-new':'merge');}
  // Ensure the permanent account row is usable even on DB-backed installations where the bundle came from local fallback storage.
  if(loom_db_ready()){
    $a=loom_user_portability_recursive_remap((array)$payload['account'],$maps);$pdo=loom_db_pdo(true);$sql="INSERT INTO loom_users(user_id,username,username_norm,email,email_norm,password_hash,privilege,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE username=VALUES(username),username_norm=VALUES(username_norm),email=VALUES(email),email_norm=VALUES(email_norm),password_hash=VALUES(password_hash),privilege=VALUES(privilege),updated_at=VALUES(updated_at)";$st=$pdo->prepare($sql);$st->execute([$target,(string)$a['username'],loom_username_norm((string)$a['username']),(string)$a['email'],loom_email_norm((string)$a['email']),(string)$a['passwordHash'],(string)($a['privilege']??'User'),loom_db_dt((string)($a['createdAt']??''))?:gmdate('Y-m-d H:i:s.000'),loom_db_dt((string)($a['updatedAt']??''))?:gmdate('Y-m-d H:i:s.000')]);
    foreach((array)($payload['graph']['clientIds']??[]) as $cid){$cid=safe_token((string)$cid);if($cid==='')continue;try{$pdo->prepare("INSERT INTO loom_user_clients(client_id,user_id,linked_at) VALUES(?,?,UTC_TIMESTAMP(3)) ON DUPLICATE KEY UPDATE user_id=VALUES(user_id)")->execute([$cid,$target]);$pdo->prepare("UPDATE loom_clients SET user_id=? WHERE client_id=?")->execute([$target,$cid]);}catch(Throwable $e){}}
  }
  loom_audit_record('backup.user.imported',['details'=>['sourceUserId'=>$payload['account']['userId']??null,'targetUserId'=>$target,'mode'=>$preview['mode'],'projectRefs'=>$payload['projectRefs']??[],'database'=>$dbResult]],'Portable LOOM user restored.');return ['status'=>'restored','sourceUserId'=>$payload['account']['userId']??null,'targetUserId'=>$target,'mode'=>$preview['mode'],'local'=>$local,'streamRows'=>$streams,'assetFiles'=>$assets,'database'=>$dbResult,'systemOwnerTransferred'=>false,'rollback'=>$rollback];
}
