<?php
// @loom-file release=0.15.55 revision=9 policy=package-priority
require __DIR__.'/_common.php';
if(($_SERVER['REQUEST_METHOD']??'POST')!=='POST')json_out(['ok'=>false,'error'=>'POST required'],405);$body=json_decode((string)file_get_contents('php://input'),true);if(!is_array($body))json_out(['ok'=>false,'error'=>'Invalid JSON'],400);$clientId=safe_token((string)($body['clientId']??''));loom_require_admin($clientId);$action=(string)($body['action']??'list');
function identity_confirm(array $b): void { if((string)($b['confirmPhrase']??'')!=='CONFIRM')throw new RuntimeException('Type CONFIRM to perform this identity operation.'); }
function identity_active_guest(string $guestId): array { $g=loom_guest_get($guestId);if(!$g)throw new RuntimeException('Guest identity not found.');if(($g['status']??'')==='merged')throw new RuntimeException('That Guest Identity has already been merged into '.($g['mergedIntoGuestId']??'its canonical target').'. Open the canonical Guest Identity instead.');return $g; }
function identity_user_clients(string $userId): array {
  $userId=safe_token($userId);if($userId==='')return [];$out=[];$temp=loom_temp_account_store();foreach(($temp['clients']??[]) as $cid=>$uid)if((string)$uid===$userId)$out[safe_token((string)$cid)]=true;
  if(loom_db_ready())try{$st=loom_db_pdo(true)->prepare("SELECT client_id FROM loom_user_clients WHERE user_id=?");$st->execute([$userId]);foreach($st->fetchAll() as $r){$cid=safe_token((string)($r['client_id']??''));if($cid!=='')$out[$cid]=true;}}catch(Throwable $e){}
  return array_values(array_filter(array_keys($out)));
}
function identity_user_display_name(string $uid,array $u,?array $gp,array $guests=[]): string {
  // Human-facing name is not a uniqueness key. Prefer the newest attached guest's
  // explicit display name so legacy storage handles such as `MichaelYebba 2` or
  // `GuestHandle-*` never leak into the unified Users directory.
  usort($guests,fn($a,$b)=>strcmp((string)($b['attachedAt']??$b['updatedAt']??''),(string)($a['attachedAt']??$a['updatedAt']??'')));
  foreach($guests as $g){$cid=safe_token((string)($g['primaryClientId']??''));if($cid==='')continue;$p=loom_guest_profile_for_client($cid);if(!$p)continue;$pub=loom_guest_profile_public($p);$n=loom_clean_username((string)($pub['displayName']??''));if($n!==''&&!preg_match('/^GuestHandle-/i',$n))return $n;}
  $n=loom_clean_username(function_exists('loom_global_profile_display_name')?loom_global_profile_display_name((array)$gp):(string)($gp['displayName']??$gp['username']??''));if($n!==''&&!preg_match('/^(?:GuestHandle-|acct_)/i',$n))return $n;
  $email=trim((string)($u['email']??''));return $email!==''?$email:('User '.strtoupper(substr(preg_replace('/[^A-Za-z0-9]/','',$uid),-6)));
}
function identity_user_rows(): array {
  $out=[];$push=function(array $u)use(&$out){$uid=safe_token((string)($u['user_id']??$u['userId']??''));if($uid==='')return;$gp=loom_global_profile_get('user',$uid);$guests=loom_guest_list_for_user($uid);$ips=loom_identity_ip_history_enriched('user',$uid,false,0);$out[$uid]=['kind'=>'permanent','userId'=>$uid,'displayName'=>identity_user_display_name($uid,$u,$gp,$guests),'email'=>$u['email']??null,'privilege'=>$u['privilege']??'User','createdAt'=>$u['created_at']??$u['createdAt']??null,'updatedAt'=>$u['updated_at']??$u['updatedAt']??null,'globalProfile'=>$gp,'clientCount'=>count(identity_user_clients($uid)),'guestHistoryCount'=>count($guests),'lastNetwork'=>$ips[0]??null];};
  if(loom_db_ready())try{foreach(loom_db_pdo(true)->query("SELECT user_id,email,privilege,created_at,updated_at FROM loom_users ORDER BY updated_at DESC") as $u)$push($u);}catch(Throwable $e){}else foreach((loom_temp_account_store()['users']??[]) as $u)$push($u);
  $rows=array_values($out);usort($rows,fn($a,$b)=>strcasecmp((string)($a['displayName']??''),(string)($b['displayName']??'')));return $rows;
}
function identity_guest_rows(): array {
  $out=[];
  foreach(loom_guest_all() as $g){
    $uid=safe_token((string)($g['attachedUserId']??''));
    $cid=(string)($g['primaryClientId']??'');$guestProfile=loom_guest_profile_for_client($cid);$guestPublic=is_array($guestProfile)?loom_guest_profile_public($guestProfile):[];
    $profile=$uid!==''?loom_global_profile_get('user',$uid):loom_global_profile_get('client',$cid);
    $username=loom_clean_username(function_exists('loom_global_profile_display_name')?loom_global_profile_display_name((array)$profile):(string)($profile['displayName']??$profile['username']??''));$visible=loom_clean_username((string)($guestPublic['displayName']??''));
    $email=null;
    if($uid!==''){$u=loom_account_user_by_id($uid);$email=is_array($u)?($u['email']??null):null;}
    $g['kind']='guest';$g['username']=$username!==''&&!preg_match('/^GuestHandle-/i',$username)?$username:null;$g['displayName']=$visible!==''?$visible:($g['username']?:('Guest '.strtoupper(substr(preg_replace('/[^A-Za-z0-9]/','',(string)($g['guestId']??'')),-6))));$g['email']=$email;$ips=$cid!==''?loom_identity_ip_history_enriched('client',$cid,false,0):[];$g['lastNetwork']=$ips[0]??null;$cs=loom_continuity_read_store();$lock=$cs['guestLocks'][$g['guestId']]??null;$g['permanentRequired']=is_array($lock)&&!empty($lock['required']);$g['ambiguityLabels']=is_array($lock)?array_values((array)($lock['labels']??[])):[];
    $out[]=$g;
  }
  usort($out,fn($a,$b)=>strcasecmp((string)($a['displayName']??''),(string)($b['displayName']??'')));
  return $out;
}
try{
  if($action==='list'){ $backfilled=function_exists('loom_continuity_backfill_historical_overlap_locks')?loom_continuity_backfill_historical_overlap_locks():0;json_out(['ok'=>true,'guests'=>identity_guest_rows(),'users'=>identity_user_rows(),'geo'=>loom_geo_status(),'backfilledGuests'=>$backfilled,'legacyDiscoveryDeferred'=>false]); }
  if($action==='detail'){ $detail=loom_guest_detail((string)($body['guestId']??''));$g=$detail['guest']??[];$cid=safe_token((string)($g['primaryClientId']??''));$gp=$cid!==''?loom_guest_profile_for_client($cid):null;$pub=is_array($gp)?loom_guest_profile_public($gp):[];$uid=safe_token((string)($g['attachedUserId']??''));$profile=$uid!==''?loom_global_profile_get('user',$uid):($detail['globalProfile']??[]);$detail['displayUsername']=loom_clean_username((string)($pub['displayName']??''))?:loom_clean_username(function_exists('loom_global_profile_display_name')?loom_global_profile_display_name((array)$profile):(string)($profile['displayName']??$profile['username']??''));$detail['ipHistory']=$cid!==''?loom_identity_ip_history_enriched('client',$cid,true,5):[];$cs=loom_continuity_read_store();$detail['guestLock']=$cs['guestLocks'][$g['guestId']??'']??null;json_out(['ok'=>true,'detail'=>$detail,'users'=>identity_user_rows(),'geo'=>loom_geo_status()]); }
  if($action==='user-detail'){ $uid=safe_token((string)($body['userId']??''));$u=loom_account_user_by_id($uid);if(!$u)throw new RuntimeException('Permanent account not found.');$clients=identity_user_clients($uid);$profiles=[];foreach($clients as $cid){$gp=loom_guest_profile_for_client($cid);if($gp)$profiles[]=loom_guest_profile_public($gp);}$guests=loom_guest_list_for_user($uid);$gp=loom_global_profile_get('user',$uid);$detail=['kind'=>'permanent','userId'=>$uid,'displayName'=>identity_user_display_name($uid,$u,$gp,$guests),'account'=>$u,'globalProfile'=>$gp,'clients'=>$clients,'guestHistories'=>$guests,'projectIdentities'=>loom_project_identity_list_for_owner('user',$uid),'ipHistory'=>loom_identity_ip_history_enriched('user',$uid,true,8),'guestProfiles'=>$profiles,'storageMode'=>loom_db_ready()?'database':'durable-local'];json_out(['ok'=>true,'detail'=>$detail,'geo'=>loom_geo_status()]); }
  if($action==='geo-settings-save'){identity_confirm($body);json_out(['ok'=>true,'geo'=>['settings'=>loom_geo_write_settings(is_array($body['settings']??null)?$body['settings']:[]),'cachedLocations'=>count(loom_geo_cache()['items']??[]),'note'=>'Approximate IP geolocation is display-only and never identity evidence.']]);}
  if($action==='geo-cache-clear'){identity_confirm($body);$n=loom_geo_clear_cache();json_out(['ok'=>true,'cleared'=>$n,'geo'=>loom_geo_status()]);}
  if($action==='issue-recovery'){identity_confirm($body);$gid=safe_token((string)($body['guestId']??''));identity_active_guest($gid);$r=loom_guest_issue_recovery_code($gid,'admin');loom_admin_audit('guest.recovery.issue','guest',$gid,'',['identityOperation'=>true]);json_out(['ok'=>true]+$r);}
  if($action==='attach'){identity_confirm($body);$gid=safe_token((string)($body['guestId']??''));$uid=safe_token((string)($body['userId']??''));$g=identity_active_guest($gid);if(!loom_account_user_by_id($uid))throw new RuntimeException('Permanent user not found.');$admin=loom_auth_user();$adminId=(string)($admin['user_id']??$admin['userId']??'');$a=loom_guest_attach_client_to_user((string)$g['primaryClientId'],$uid,'admin',$adminId,'admin-attach');loom_admin_audit('guest.attach','guest',$gid,'',['userId'=>$uid,'attachmentId'=>$a['attachmentId']??null]);json_out(['ok'=>true,'attachment'=>$a,'detail'=>loom_guest_detail($gid)]);}
  if($action==='convert'){identity_confirm($body);$gid=safe_token((string)($body['guestId']??''));$email=trim((string)($body['email']??''));$password=(string)($body['password']??'');$g=identity_active_guest($gid);if(($g['status']??'')==='attached')throw new RuntimeException('Guest identity is already attached.');$u=loom_create_account_record($email,$password,'User');$uid=(string)($u['user_id']??$u['userId']??'');$admin=loom_auth_user();$adminId=(string)($admin['user_id']??$admin['userId']??'');$a=loom_guest_attach_client_to_user((string)$g['primaryClientId'],$uid,'admin',$adminId,'admin-convert');loom_admin_audit('guest.convert-to-account','guest',$gid,'',['userId'=>$uid,'email'=>$email]);if(function_exists('loom_email_notify_user'))try{loom_email_notify_user('welcome',$u);}catch(Throwable $e){}json_out(['ok'=>true,'userId'=>$uid,'attachment'=>$a,'detail'=>loom_guest_detail($gid)]);}
  if($action==='merge-guests'){identity_confirm($body);$source=safe_token((string)($body['sourceGuestId']??''));$target=safe_token((string)($body['targetGuestId']??''));identity_active_guest($source);identity_active_guest($target);$admin=loom_auth_user();$adminId=(string)($admin['user_id']??$admin['userId']??'');$m=loom_guest_admin_merge($source,$target,$adminId);loom_admin_audit('guest.merge','guest',$source,'',['targetGuestId'=>$target,'summary'=>$m['summary']]);json_out(['ok'=>true,'merge'=>$m,'detail'=>loom_guest_detail($target)]);}
}catch(Throwable $e){json_out(['ok'=>false,'error'=>$e->getMessage()],409);}json_out(['ok'=>false,'error'=>'Unknown action'],400);
