<?php
// @loom-file release=0.15.65 revision=15 policy=package-priority
// Canonical LOOM people directory. Permanent accounts and Guest Identities are
// one Admin surface; raw browser clients are evidence/lineage, never people.
require __DIR__.'/_common.php';
if(($_SERVER['REQUEST_METHOD']??'GET')!=='POST')json_out(['ok'=>false,'error'=>'POST required'],405);
$body=json_decode((string)file_get_contents('php://input'),true);if(!is_array($body))json_out(['ok'=>false,'error'=>'Invalid JSON'],400);
$action=(string)($body['action']??'list');$requestClientId=safe_token((string)($body['clientId']??''));$project=safe_slug((string)($body['project']??''));
loom_require_admin($requestClientId);if(function_exists('loom_access_reconcile_system_owner_identity'))loom_access_reconcile_system_owner_identity($requestClientId);if($requestClientId!=='')loom_capture_request_ip($requestClientId,$project);

function au_confirm(array $body): void { if((string)($body['confirmPhrase']??'')!=='CONFIRM')throw new RuntimeException('Type CONFIRM to authorize this administrator change.'); }
function au_admin_user_id(): string {$u=loom_auth_user();return safe_token((string)($u['user_id']??$u['userId']??''));}
function au_norm_user(array $u): array {return ['userId'=>safe_token((string)($u['user_id']??$u['userId']??'')),'accountHandle'=>(string)($u['username']??''),'email'=>(string)($u['email']??''),'privilege'=>(string)($u['privilege']??'User'),'createdAt'=>$u['created_at']??$u['createdAt']??null,'updatedAt'=>$u['updated_at']??$u['updatedAt']??null];}
function au_users(): array {$out=[];$temp=loom_temp_account_store();foreach(($temp['users']??[]) as $u){$n=au_norm_user($u);if($n['userId']!=='')$out[$n['userId']]=$n;}if(loom_db_ready())try{foreach(loom_db_pdo(true)->query("SELECT user_id,username,email,privilege,created_at,updated_at FROM loom_users")->fetchAll() as $u){$n=au_norm_user($u);if($n['userId']!=='')$out[$n['userId']]=$n;}}catch(Throwable $e){}return $out;}
function au_client_map(): array {$out=[];$temp=loom_temp_account_store();foreach(($temp['clients']??[]) as $cid=>$uid){$cid=safe_token((string)$cid);$uid=safe_token((string)$uid);if($cid!==''&&$uid!=='')$out[$cid]=$uid;}if(loom_db_ready())try{foreach(loom_db_pdo(true)->query("SELECT client_id,user_id FROM loom_user_clients")->fetchAll() as $r){$cid=safe_token((string)$r['client_id']);$uid=safe_token((string)$r['user_id']);if($cid!==''&&$uid!=='')$out[$cid]=$uid;}foreach(loom_db_pdo(true)->query("SELECT client_id,user_id FROM loom_clients WHERE user_id IS NOT NULL AND user_id<>''")->fetchAll() as $r){$cid=safe_token((string)$r['client_id']);$uid=safe_token((string)$r['user_id']);if($cid!==''&&$uid!=='')$out[$cid]=$uid;}}catch(Throwable $e){}return $out;}
function au_profiles(): array {$out=[];foreach(glob(loom_data_dir().'/users/*.json')?:[] as $f){if(in_array(basename($f),['network.json','project-identities.json'],true))continue;$p=read_json_file($f);$cid=safe_token((string)($p['clientId']??''));if($cid!=='')$out[$cid]=$p;}if(loom_db_ready())try{$pdo=loom_db_pdo(true);foreach($pdo->query("SELECT * FROM loom_client_profiles")->fetchAll() as $r){$cid=safe_token((string)$r['client_id']);if($cid==='')continue;$p=json_decode((string)($r['payload_json']??''),true);if(!is_array($p))$p=[];$p['clientId']=$cid;$p['createdAt']=$p['createdAt']??$r['created_at'];$p['updatedAt']=$p['updatedAt']??$r['updated_at'];$out[$cid]=array_replace($out[$cid]??[],$p);}foreach($pdo->query("SELECT client_id,first_seen,last_seen,user_label,metadata FROM loom_clients")->fetchAll() as $r){$cid=safe_token((string)$r['client_id']);if($cid==='')continue;$out[$cid]=array_replace(['clientId'=>$cid],$out[$cid]??[],['_clientFirstSeen'=>$r['first_seen'],'_clientLastSeen'=>$r['last_seen'],'_userLabel'=>$r['user_label'],'_metadata'=>json_decode((string)($r['metadata']??''),true)]);}}catch(Throwable $e){}return $out;}
function au_user_clients(string $uid): array {
  $uid=safe_token($uid);$out=[];$current=au_client_map();foreach($current as $cid=>$u)if($u===$uid)$out[$cid]=true;
  /* Attached Guest Histories are an explicit, verified lineage link too. */foreach(loom_guest_list_for_user($uid) as $g){$root=loom_guest_root($g);foreach(array_keys((array)($root['clients']??[])) as $cid){$cid=safe_token((string)$cid);if($cid!==''&&str_starts_with($cid,'client_'))$out[$cid]=true;}$cid=safe_token((string)($root['primaryClientId']??''));if($cid!==''&&str_starts_with($cid,'client_'))$out[$cid]=true;}
  /* v0.15.58: legacy client-profile userId is historical authenticated-account
     evidence. Include it only when it agrees with any current mapping and the
     permanent account itself exists, so old browser names such as PixelShift…
     remain inspectable lineage without becoming separate canonical people. */
  if(loom_account_user_by_id($uid))foreach(au_profiles() as $cid=>$profile){$historical=safe_token((string)($profile['userId']??$profile['user_id']??''));if($historical!==$uid)continue;if(isset($current[$cid])&&$current[$cid]!==$uid)continue;$out[$cid]=true;}
  return array_keys($out);
}
function au_guest_raw(string $guestId): ?array {$g=loom_guest_get($guestId);if(!$g)return null;return loom_guest_root($g);}
function au_guest_clients(string $guestId): array {$g=au_guest_raw($guestId);if(!$g)return [];$out=[];foreach(array_keys((array)($g['clients']??[])) as $cid){$cid=safe_token((string)$cid);if($cid!=='')$out[$cid]=true;}$p=safe_token((string)($g['primaryClientId']??''));if($p!=='')$out[$p]=true;return array_keys($out);}
function au_visible_name_for_user(string $uid,array $u,array $clients): string {
  // A permanent person's LOOM-wide Global Profile is canonical. Guest History
  // names are useful aliases, but must not unexpectedly replace the account's
  // chosen presentation name in the unified directory.
  $gp=loom_global_profile_get('user',$uid);$n=loom_clean_username(function_exists('loom_global_profile_display_name')?loom_global_profile_display_name((array)$gp):(string)($gp['displayName']??$gp['username']??''));if($n!==''&&!preg_match('/^(?:GuestHandle-|acct_)/i',$n))return $n;
  $guests=loom_guest_list_for_user($uid);usort($guests,fn($a,$b)=>strcmp((string)($b['attachedAt']??$b['updatedAt']??''),(string)($a['attachedAt']??$a['updatedAt']??'')));foreach($guests as $g){$cid=safe_token((string)($g['primaryClientId']??''));$p=$cid!==''?loom_guest_profile_for_client($cid):null;if($p){$n=loom_clean_username((string)(loom_guest_profile_public($p)['displayName']??''));if($n!=='')return $n;}}
  $email=trim((string)($u['email']??''));return $email!==''?$email:('User '.strtoupper(substr(preg_replace('/[^A-Za-z0-9]/','',$uid),-6)));
}
function au_visible_name_for_guest(string $gid,array $clients): string {$g=au_guest_raw($gid);$primary=safe_token((string)($g['primaryClientId']??($clients[0]??'')));if($primary!==''){$p=loom_guest_profile_for_client($primary);if($p){$n=loom_clean_username((string)(loom_guest_profile_public($p)['displayName']??''));if($n!=='')return $n;}$gp=loom_global_profile_get('client',$primary);$n=loom_clean_username(function_exists('loom_global_profile_display_name')?loom_global_profile_display_name((array)$gp):(string)($gp['displayName']??$gp['username']??''));if($n!==''&&!preg_match('/^GuestHandle-/i',$n))return $n;}if(au_is_system_owner('guest',$gid))return 'System Owner';return 'Guest '.strtoupper(substr(preg_replace('/[^A-Za-z0-9]/','',$gid),-6));}
function au_target(array $body): array {$type=strtolower(trim((string)($body['subjectType']??$body['kind']??'')));$id=safe_token((string)($body['subjectId']??$body['userId']??$body['guestId']??''));if(in_array($type,['permanent','account','permanent-account'],true))$type='user';if(in_array($type,['guest-identity','guest_identity'],true))$type='guest';if($type===''&&$id!==''){$users=au_users();if(isset($users[$id]))$type='user';elseif(loom_guest_get($id))$type='guest';elseif(str_starts_with($id,'client_'))$type='client';}if($type==='client'&&$id!==''){$u=loom_account_user_for_client($id);$uid=safe_token((string)($u['user_id']??$u['userId']??''));if($uid!=='')return ['user',$uid];$g=loom_guest_for_client($id);if($g){$g=loom_guest_root($g);return ['guest',safe_token((string)$g['guestId'])];}}if(!in_array($type,['user','guest'],true)||$id==='')throw new RuntimeException('Invalid canonical user target. Refresh the unified Users directory and retry.');return [$type,$id];}
function au_avatar_client(string $type,string $id,array $clients): ?string {if($type==='guest'){$g=au_guest_raw($id);$p=safe_token((string)($g['primaryClientId']??''));if($p!=='')return $p;}return $clients[0]??null;}
function au_avatar_version(string $type,string $id,array $clients): string {$client=au_avatar_client($type,$id,$clients);$ownerType=$type==='user'?'user':'client';$ownerId=$type==='user'?$id:(string)($client??'');$parts=['0.15.58',$type,$id];if($ownerId!==''){$p=loom_global_profile_get($ownerType,$ownerId);$parts[]=(string)($p['avatarMode']??'');$parts[]=(string)($p['updatedAt']??'');$f=loom_global_avatar_find($ownerType,$ownerId);if($f)$parts[]=(string)($f['updatedAt']??'');$legacy=loom_avatar_legacy_find_file($ownerType,$ownerId);if($legacy)$parts[]=(string)($legacy['updatedAt']??'');}if($type==='user'&&$client){$f=loom_global_avatar_find('client',$client);if($f)$parts[]=(string)($f['updatedAt']??'');$legacy=loom_avatar_legacy_find_file('client',$client);if($legacy)$parts[]=(string)($legacy['updatedAt']??'');}return substr(hash('sha256',implode('|',$parts)),0,16);} 
function au_project_avatar_meta(string $project,string $type,string $id,array $clients): array {
  $project=safe_slug($project);$ownerType=$type==='user'?'user':'client';$ownerId=$type==='user'?$id:(au_avatar_client($type,$id,$clients)??'');$identity=$ownerId!==''?loom_project_identity_get_for_owner($project,$ownerType,$ownerId):null;$clientId=au_avatar_client($type,$id,$clients);$legacyFallback=false;
  if(!$identity||(($identity['avatarMode']??'auto')==='custom'&&!loom_avatar_find_file($project,$ownerType,$ownerId))){foreach($clients as $cid){$li=loom_project_identity_get_for_owner($project,'client',$cid);$lf=loom_avatar_find_file($project,'client',$cid);if($li&&(($li['avatarMode']??'auto')==='custom'||$lf)){if(!$identity)$identity=$li;if($lf){$clientId=$cid;$legacyFallback=$ownerType!=='client'||$ownerId!==$cid;break;}}}}
  $mode=(string)($identity['avatarMode']??'auto');if($mode==='loom-default')$mode='global';if(!in_array($mode,['auto','global','project-default','custom'],true))$mode='auto';$custom=$ownerId!==''?loom_avatar_find_file($project,$ownerType,$ownerId):null;if(!$custom&&$clientId!=='')$custom=loom_avatar_find_file($project,'client',$clientId);$parts=['0.15.58',$project,$type,$id,$mode,(string)($identity['updatedAt']??''),(string)($custom['updatedAt']??''),au_avatar_version($type,$id,$clients)];$label=['custom'=>'Project custom avatar','global'=>'Global avatar inherited','project-default'=>'Project default avatar','auto'=>'Automatic project avatar'][$mode]??$mode;return ['mode'=>$mode,'label'=>$label,'customAvailable'=>(bool)$custom,'clientId'=>$clientId?:null,'legacyFallback'=>$legacyFallback,'version'=>substr(hash('sha256',implode('|',$parts)),0,16)];
}
function au_is_system_owner(string $type,string $id): bool {
  $id=safe_token($id);if($id==='')return false;$ownerUser=loom_access_system_owner_user_id();if($type==='user')return $ownerUser!==''&&hash_equals($ownerUser,$id);
  if($type==='guest'&&$ownerUser===''){$ownerClient=loom_access_system_owner_client_id();if($ownerClient==='')return false;foreach(au_guest_clients($id) as $cid)if(hash_equals($ownerClient,$cid))return true;}
  return false;
}
function au_client_lineage(string $type,string $id,array $clients): array {
  $profiles=au_profiles();$map=au_client_map();$rows=[];foreach($clients as $cid){$cid=safe_token($cid);if($cid==='')continue;$p=$profiles[$cid]??[];$gp=loom_global_profile_get('client',$cid);$names=[];foreach([(string)($gp['displayName']??''),(string)($gp['username']??''),(string)($p['username']??''),(string)($p['_userLabel']??'')] as $raw){$n=loom_clean_username($raw);if($n!==''&&!preg_match('/^(?:GuestHandle-|acct_)/i',$n))$names[$n]=true;}$historicalUser=safe_token((string)($p['userId']??$p['user_id']??''));$currentUser=safe_token((string)($map[$cid]??''));$rows[]=['clientId'=>$cid,'aliases'=>array_keys($names),'currentUserId'=>$currentUser?:null,'historicalUserId'=>$historicalUser?:null,'relationship'=>$currentUser!==''?'current-account-link':($type==='user'&&$historicalUser===$id?'historical-authenticated-account':'identity-lineage'),'firstSeen'=>$p['_clientFirstSeen']??$p['createdAt']??null,'lastSeen'=>$p['_clientLastSeen']??$p['updatedAt']??null];}
  usort($rows,fn($a,$b)=>strcmp((string)($b['lastSeen']??''),(string)($a['lastSeen']??'')));return $rows;
}
function au_owner_authority(string $type,string $id,bool $owner): array {
  $state=loom_access_system_owner_state()?:[];$ownerUser=loom_access_system_owner_user_id();$ownerClient=loom_access_system_owner_client_id();return ['isSystemOwner'=>$owner,'role'=>$owner?'system-owner':($type==='user'&&loom_access_user_is_loom_admin($id)?'loom-admin':($type==='guest'?'guest':'member')),'ownerUserId'=>$ownerUser?:null,'ownerClientId'=>$ownerClient?:null,'accountBound'=>$ownerUser!=='','bootstrapMethod'=>$state['bootstrapMethod']??null,'createdAt'=>$state['createdAt']??null,'bindingMethod'=>$state['ownerBindingMethod']??null,'bindingUpdatedAt'=>$state['ownerBindingUpdatedAt']??null];
}
function au_reconcile_user_legacy(string $uid,array $clients): void {foreach($clients as $cid){try{loom_project_identity_promote_client($cid,$uid);}catch(Throwable $e){}try{loom_project_state_attach_client($cid,$uid);}catch(Throwable $e){}try{loom_promote_client_moderation_to_user($cid,$uid);}catch(Throwable $e){}}$principal=safe_token((string)($clients[0]??''));if($principal!=='')foreach(loom_project_identity_list_for_owner('user',$uid) as $row){$project=safe_slug((string)($row['project']??''));if($project!==''&&project_dir($project))try{loom_project_identity_ensure($project,$principal,true);}catch(Throwable $e){}}}
function au_activity_index(array $clientMap): array {$idx=['user'=>[],'client'=>[]];foreach(loom_all_project_slugs() as $project){$dir=log_dir($project);foreach(is_dir($dir)?(glob($dir.'/*.jsonl')?:[]):[] as $file)foreach(@file($file,FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES)?:[] as $line){$e=json_decode($line,true);if(!is_array($e))continue;$uid=safe_token((string)($e['userId']??''));$cid=safe_token((string)($e['clientId']??''));if($uid!=='')$idx['user'][$uid][$project]=true;if($cid!==''){$idx['client'][$cid][$project]=true;if(isset($clientMap[$cid]))$idx['user'][$clientMap[$cid]][$project]=true;}}}return $idx;}
function au_projects_for_subject(string $type,string $id,array $clients,array $activityIndex): array {$out=[];$add=function($p)use(&$out){$p=safe_slug((string)$p);if($p!==''&&project_dir($p))$out[$p]=true;};if($type==='user'){foreach(loom_project_identity_list_for_owner('user',$id) as $r)$add($r['project']??'');foreach(loom_project_state_rows_for_owner('user',$id) as $r)$add($r['project']??'');foreach(array_keys($activityIndex['user'][$id]??[]) as $p)$add($p);}foreach($clients as $cid){foreach(loom_project_identity_list_for_owner('client',$cid) as $r)$add($r['project']??'');foreach(loom_project_state_rows_for_owner('client',$cid) as $r)$add($r['project']??'');foreach(loom_identity_ip_history('client',$cid) as $r)$add($r['lastProject']??'');foreach(array_keys($activityIndex['client'][$cid]??[]) as $p)$add($p);}ksort($out);return array_keys($out);}
function au_last_seen(string $type,string $id,array $clients,array $profiles,?array $user=null): ?string {$vals=[];if($user){foreach(['updatedAt','createdAt'] as $k)if(!empty($user[$k]))$vals[]=(string)$user[$k];}foreach($clients as $cid){$p=$profiles[$cid]??[];foreach(['updatedAt','createdAt','_clientLastSeen','_clientFirstSeen'] as $k)if(!empty($p[$k]))$vals[]=(string)$p[$k];foreach(loom_identity_ip_history('client',$cid) as $r)if(!empty($r['lastSeen']))$vals[]=(string)$r['lastSeen'];}if($type==='user')foreach(loom_identity_ip_history('user',$id) as $r)if(!empty($r['lastSeen']))$vals[]=(string)$r['lastSeen'];rsort($vals);return $vals[0]??null;}
function au_network_for_subject(string $type,string $id,array $clients,bool $enrich=false): array {$rows=[];$seen=[];$add=function(array $r)use(&$rows,&$seen){$ip=(string)($r['ip']??'');$key=$ip.'|'.(string)($r['lastSeen']??'');if($ip!==''&&!isset($seen[$key])){$seen[$key]=true;$rows[]=$r;}};if($type==='user')foreach(loom_identity_ip_history_enriched('user',$id,$enrich,$enrich?8:0) as $r)$add($r);foreach($clients as $cid)foreach(loom_identity_ip_history_enriched('client',$cid,$enrich,$enrich?8:0) as $r)$add($r);usort($rows,fn($a,$b)=>strcmp((string)($b['lastSeen']??''),(string)($a['lastSeen']??'')));return $rows;}
function au_subject_project_role(string $project,string $type,string $id,array $clients): string {
  $project=safe_slug($project);if(au_is_system_owner($type,$id))return 'system-owner';if($type==='user'&&loom_access_user_is_loom_admin($id))return 'loom-admin';$grants=loom_access_store()['projectGrants'][$project]??[];if(!is_array($grants))return 'member';$keys=[];if($type==='user')$keys[]='user:'.$id;elseif($type==='guest')$keys[]='guest:'.$id;foreach($clients as $cid){$cid=safe_token((string)$cid);if($cid!=='')$keys[]='client:'.$cid;}foreach($keys as $key){$r=$grants[$key]??null;if(!is_array($r)||!($r['enabled']??true))continue;$role=(string)($r['role']??'');if(in_array($role,['project-admin','project-manager'],true))return $role;}return 'member';
}
function au_activity(string $project,string $type,string $id,array $clients): array {$project=safe_slug($project);if($project===''||!project_dir($project))return ['eventCount'=>0,'sessionCount'=>0,'userActionCount'=>0,'failureCount'=>0,'firstSeen'=>null,'lastSeen'=>null,'recentSessions'=>[],'topActions'=>[]];$clientSet=array_fill_keys($clients,true);$sessions=[];$events=0;$actions=0;$fail=0;$first=null;$last=null;$top=[];foreach(glob(log_dir($project).'/*.jsonl')?:[] as $file)foreach(@file($file,FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES)?:[] as $line){$e=json_decode($line,true);if(!is_array($e))continue;$match=$type==='user'?(((string)($e['userId']??''))===$id||isset($clientSet[(string)($e['clientId']??'')])):isset($clientSet[(string)($e['clientId']??'')]);if(!$match)continue;$events++;$ts=(string)($e['serverTimestamp']??$e['clientTimestamp']??'');if($ts!==''){$first=$first===null?$ts:min($first,$ts);$last=$last===null?$ts:max($last,$ts);}if(($e['type']??'')==='action.state'&&($e['kind']??'')==='user'&&($e['state']??'')==='active')$actions++;if(($e['state']??'')==='failed'||str_contains((string)($e['type']??''),'error'))$fail++;$aid=(string)($e['actionId']??'');if($aid!=='')$top[$aid]=($top[$aid]??0)+1;$sid=(string)($e['sessionId']??'');if($sid!==''){$r=$sessions[$sid]??['sessionId'=>$sid,'clientId'=>$e['clientId']??null,'firstSeen'=>null,'lastSeen'=>null,'eventCount'=>0];$r['eventCount']++;if($ts!==''){$r['firstSeen']=$r['firstSeen']===null?$ts:min($r['firstSeen'],$ts);$r['lastSeen']=$r['lastSeen']===null?$ts:max($r['lastSeen'],$ts);}$sessions[$sid]=$r;}}$recent=array_values($sessions);usort($recent,fn($a,$b)=>strcmp((string)($b['lastSeen']??''),(string)($a['lastSeen']??'')));arsort($top);$tops=[];foreach(array_slice($top,0,10,true) as $k=>$v)$tops[]=['actionId'=>$k,'count'=>$v];return ['eventCount'=>$events,'sessionCount'=>count($sessions),'userActionCount'=>$actions,'failureCount'=>$fail,'firstSeen'=>$first,'lastSeen'=>$last,'recentSessions'=>array_slice($recent,0,10),'topActions'=>$tops];}
function au_project_summary(string $project,string $type,string $id,array $clients): array {$project=safe_slug($project);$ownerType=$type==='user'?'user':'client';$ownerId=$type==='user'?$id:(au_avatar_client($type,$id,$clients)??'');$identity=$ownerId!==''?loom_project_identity_get_for_owner($project,$ownerType,$ownerId):null;if(!$identity)foreach($clients as $cid){$legacy=loom_project_identity_get_for_owner($project,'client',$cid);if($legacy){$identity=$legacy;break;}}$principal=au_avatar_client($type,$id,$clients)??'';$role=au_subject_project_role($project,$type,$id,$clients);$state=in_array($type,['user','guest'],true)?loom_identity_project_ban_state($project,$type,$id):['banned'=>false,'includeData'=>false];$legacyBanned=false;foreach($clients as $cid){$ls=loom_project_subject_state($project,'client',$cid);if(!empty($ls['banned']))$legacyBanned=true;}if($type==='user'){$ls=loom_project_subject_state($project,'user',$id);if(!empty($ls['banned']))$legacyBanned=true;}$activity=au_activity($project,$type,$id,$clients);$avatar=au_project_avatar_meta($project,$type,$id,$clients);return ['project'=>$project,'name'=>humanize_project_slug($project),'identity'=>$identity,'avatar'=>$avatar,'role'=>$role,'banned'=>(bool)($state['banned']??false)||(bool)$legacyBanned,'canonicalBan'=>$state,'legacyBanned'=>$legacyBanned,'activity'=>$activity];}
function au_referral_summary(string $type,string $id,array $clients): array {$s=loom_referral_read_store();$shares=0;$clicks=0;$refs=0;$self=0;$referredBy=null;$guestIds=[];if($type==='guest')$guestIds[$id]=true;else foreach(loom_guest_list_for_user($id) as $g){$gid=safe_token((string)($g['canonicalGuestId']??$g['guestId']??''));if($gid!=='')$guestIds[$gid]=true;}foreach(($s['shares']??[]) as $r){$ref=(array)($r['referrer']??[]);$match=$type==='user'&&safe_token((string)($ref['userId']??''))===$id;$gid=safe_token((string)($ref['guestId']??''));if(!$match&&$gid!==''&&isset($guestIds[$gid]))$match=true;if($match){$shares++;$clicks+=(int)($r['clicks']??0);$refs+=(int)($r['referrals']??0);$self+=(int)($r['selfVisits']??0);}}foreach(($s['acceptances']??[]) as $a){$v=(array)($a['visitor']??[]);$match=$type==='user'&&safe_token((string)($v['userId']??''))===$id;$gid=safe_token((string)($v['guestId']??''));if(!$match&&$gid!==''&&isset($guestIds[$gid]))$match=true;if($match){$referredBy=['username'=>$a['referrer']['username']??'LOOM User','project'=>$a['project']??null,'createdAt'=>$a['createdAt']??null];break;}}return ['shareLinks'=>$shares,'clicks'=>$clicks,'referrals'=>$refs,'selfVisits'=>$self,'referredBy'=>$referredBy];}
function au_continuity_summary(string $type,string $id,array $clients): array {$s=loom_continuity_read_store();$locks=[];$clusters=[];if($type==='guest'){$r=$s['guestLocks'][$id]??null;if(is_array($r))$locks[]=$r;}else foreach(loom_guest_list_for_user($id) as $g){$gid=(string)($g['canonicalGuestId']??$g['guestId']??'');$r=$s['guestLocks'][$gid]??null;if(is_array($r))$locks[]=$r;}foreach($clients as $cid){$r=$s['clients'][$cid]??null;if(is_array($r)&&!empty($r['clusterId']))$clusters[(string)$r['clusterId']]=true;}return ['clusterIds'=>array_keys($clusters),'guestLocks'=>$locks,'permanentRequired'=>count($locks)>0];}
function au_directory(string $focusProject=''): array {$focusProject=safe_slug($focusProject);if($focusProject!==''&&!project_dir($focusProject))$focusProject='';$users=au_users();$map=au_client_map();$profiles=au_profiles();$activity=au_activity_index($map);$rows=[];foreach($users as $uid=>$u){$clients=au_user_clients($uid);au_reconcile_user_legacy($uid,$clients);loom_global_profile_ensure_for_owner('user',$uid);$projects=au_projects_for_subject('user',$uid,$clients,$activity);if($focusProject!==''&&!in_array($focusProject,$projects,true))continue;$net=au_network_for_subject('user',$uid,$clients,false);$global=loom_identity_global_ban_state('user',$uid);$focused=$focusProject!==''?loom_identity_project_ban_state($focusProject,'user',$uid):null;$rows[]=['subjectType'=>'user','subjectId'=>$uid,'kind'=>'permanent','displayName'=>au_visible_name_for_user($uid,$u,$clients),'email'=>$u['email'],'privilege'=>$u['privilege'],'systemOwner'=>au_is_system_owner('user',$uid),'loomAdmin'=>loom_access_user_is_loom_admin($uid),'clientCount'=>count($clients),'guestHistoryCount'=>count(loom_guest_list_for_user($uid)),'projects'=>$projects,'projectCount'=>count($projects),'lastSeen'=>au_last_seen('user',$uid,$clients,$profiles,$u),'avatarClientId'=>au_avatar_client('user',$uid,$clients),'avatarVersion'=>au_avatar_version('user',$uid,$clients),'projectAvatarVersion'=>$focusProject!==''?au_project_avatar_meta($focusProject,'user',$uid,$clients)['version']:null,'projectAvatarClientId'=>$focusProject!==''?au_project_avatar_meta($focusProject,'user',$uid,$clients)['clientId']:null,'lastNetwork'=>$net[0]??null,'globalBanned'=>(bool)$global['banned'],'projectBanned'=>(bool)($focused['banned']??false)];}
  $store=loom_guest_store();$seen=[];foreach(($store['guests']??[]) as $raw){if(!is_array($raw))continue;$g=loom_guest_root($raw);$gid=safe_token((string)($g['guestId']??''));if($gid===''||isset($seen[$gid]))continue;$seen[$gid]=true;if(($g['status']??'')==='merged'||safe_token((string)($g['attachedUserId']??''))!=='')continue;$clients=au_guest_clients($gid);if($clients)loom_global_profile_ensure_for_owner('client',$clients[0]);$projects=au_projects_for_subject('guest',$gid,$clients,$activity);if($focusProject!==''&&!in_array($focusProject,$projects,true))continue;$net=au_network_for_subject('guest',$gid,$clients,false);$global=loom_identity_global_ban_state('guest',$gid);$focused=$focusProject!==''?loom_identity_project_ban_state($focusProject,'guest',$gid):null;$cs=loom_continuity_read_store();$lock=$cs['guestLocks'][$gid]??null;$rows[]=['subjectType'=>'guest','subjectId'=>$gid,'kind'=>'guest','displayName'=>au_visible_name_for_guest($gid,$clients),'email'=>null,'privilege'=>au_is_system_owner('guest',$gid)?'System Owner':'Guest','systemOwner'=>au_is_system_owner('guest',$gid),'loomAdmin'=>false,'clientCount'=>count($clients),'guestHistoryCount'=>0,'projects'=>$projects,'projectCount'=>count($projects),'lastSeen'=>au_last_seen('guest',$gid,$clients,$profiles,null),'avatarClientId'=>au_avatar_client('guest',$gid,$clients),'avatarVersion'=>au_avatar_version('guest',$gid,$clients),'projectAvatarVersion'=>$focusProject!==''?au_project_avatar_meta($focusProject,'guest',$gid,$clients)['version']:null,'projectAvatarClientId'=>$focusProject!==''?au_project_avatar_meta($focusProject,'guest',$gid,$clients)['clientId']:null,'lastNetwork'=>$net[0]??null,'globalBanned'=>(bool)$global['banned'],'projectBanned'=>(bool)($focused['banned']??false),'permanentRequired'=>is_array($lock)&&!empty($lock['required']),'ambiguityLabels'=>is_array($lock)?array_values((array)($lock['labels']??[])):[]];}
  usort($rows,fn($a,$b)=>strcasecmp((string)$a['displayName'],(string)$b['displayName']));return ['scope'=>$focusProject!==''?'project':'global','project'=>$focusProject?:null,'total'=>count($rows),'users'=>$rows,'projects'=>loom_all_project_slugs()];}
function au_detail(string $type,string $id,string $focusProject=''): array {[$type,$id]=[$type,safe_token($id)];$users=au_users();$profiles=au_profiles();if($type==='user'){$u=$users[$id]??null;if(!$u)throw new RuntimeException('Permanent account not found.');$clients=au_user_clients($id);au_reconcile_user_legacy($id,$clients);$name=au_visible_name_for_user($id,$u,$clients);$account=$u;$guestHistories=loom_guest_list_for_user($id);$globalProfile=loom_global_profile_ensure_for_owner('user',$id);}else{$g=au_guest_raw($id);if(!$g||safe_token((string)($g['guestId']??''))!==$id)throw new RuntimeException('Guest Identity not found.');$clients=au_guest_clients($id);$name=au_visible_name_for_guest($id,$clients);$account=null;$guestHistories=[];$globalProfile=($clients?loom_global_profile_ensure_for_owner('client',$clients[0]):null);}
  $activityIdx=au_activity_index(au_client_map());$projectIds=au_projects_for_subject($type,$id,$clients,$activityIdx);$summaries=[];foreach($projectIds as $p)$summaries[$p]=au_project_summary($p,$type,$id,$clients);$focusProject=safe_slug($focusProject);if($focusProject!==''&&project_dir($focusProject)&&!isset($summaries[$focusProject]))$summaries[$focusProject]=au_project_summary($focusProject,$type,$id,$clients);$net=au_network_for_subject($type,$id,$clients,true);$clientProfiles=[];foreach($clients as $cid)if(isset($profiles[$cid]))$clientProfiles[]=$profiles[$cid];$global=loom_identity_global_ban_state($type,$id);$owner=au_is_system_owner($type,$id);$principal=au_avatar_client($type,$id,$clients);$guestIdentity=$type==='guest'?au_guest_raw($id):null;return ['subjectType'=>$type,'subjectId'=>$id,'kind'=>$type==='user'?'permanent':'guest','displayName'=>$name,'account'=>$account,'email'=>$account['email']??null,'privilege'=>$account['privilege']??'Guest','systemOwner'=>$owner,'loomAdmin'=>$type==='user'?loom_access_user_is_loom_admin($id):false,'globalProfile'=>$globalProfile,'guestIdentity'=>$guestIdentity,'clients'=>$clients,'clientProfiles'=>$clientProfiles,'clientLineage'=>au_client_lineage($type,$id,$clients),'guestHistories'=>$guestHistories,'authority'=>au_owner_authority($type,$id,$owner),'avatarClientId'=>$principal?:null,'avatarVersion'=>au_avatar_version($type,$id,$clients),'ipHistory'=>$net,'lastNetwork'=>$net[0]??null,'globalBan'=>$global,'projects'=>array_values($summaries),'focusedProject'=>$focusProject!==''?($summaries[$focusProject]??null):null,'referrals'=>au_referral_summary($type,$id,$clients),'continuity'=>au_continuity_summary($type,$id,$clients),'storageMode'=>loom_db_ready()?'database':'durable-local'];}
function au_update_email(string $userId,string $email): void {$email=trim($email);if(!filter_var($email,FILTER_VALIDATE_EMAIL))throw new RuntimeException('Enter a valid email address.');$other=loom_account_user_by_email($email);$otherId=safe_token((string)($other['user_id']??$other['userId']??''));if($other&&$otherId!==$userId)throw new RuntimeException('That email is already registered.');if(loom_db_ready()){$pdo=loom_db_pdo(true);$pdo->prepare("UPDATE loom_users SET email=?,email_norm=?,updated_at=UTC_TIMESTAMP(3) WHERE user_id=?")->execute([$email,loom_email_norm($email),$userId]);}else{$s=loom_temp_account_store();if(!isset($s['users'][$userId]))throw new RuntimeException('User account not found.');$s['users'][$userId]['email']=$email;$s['users'][$userId]['emailNorm']=loom_email_norm($email);$s['users'][$userId]['updatedAt']=server_timestamp();loom_write_temp_account_store($s);}}

try{
  if($action==='list'){if(function_exists('loom_continuity_backfill_historical_overlap_locks'))loom_continuity_backfill_historical_overlap_locks();json_out(['ok'=>true]+au_directory($project)+['geo'=>loom_geo_status()]);}
  if($action==='detail'){[$type,$id]=au_target($body);json_out(['ok'=>true,'user'=>au_detail($type,$id,$project),'projects'=>loom_all_project_slugs(),'geo'=>loom_geo_status()]);}
  if($action==='set-global-ban'){au_confirm($body);[$type,$id]=au_target($body);$banned=(bool)($body['banned']??false);if(au_is_system_owner($type,$id))throw new RuntimeException('The System Owner cannot be globally banned.');$row=loom_set_identity_moderation_state('global','',$type,$id,$banned,false,au_admin_user_id());loom_admin_audit($banned?'user.global.ban':'user.global.unban',$type,$id,'',['canonical'=>true]);json_out(['ok'=>true,'message'=>$banned?'User banned from LOOM. Their identity and data were retained.':'Global LOOM ban removed.','user'=>au_detail($type,$id,$project)]);}
  if($action==='set-project-ban'){au_confirm($body);[$type,$id]=au_target($body);$p=safe_slug((string)($body['project']??''));if($p===''||!project_dir($p))throw new RuntimeException('Choose a valid project.');$banned=(bool)($body['banned']??false);if(au_is_system_owner($type,$id))throw new RuntimeException('The System Owner cannot be project-banned.');$row=loom_set_identity_moderation_state('project',$p,$type,$id,$banned,(bool)($body['includeData']??false),au_admin_user_id());loom_admin_audit($banned?'user.project.ban':'user.project.unban',$type,$id,$p,['canonical'=>true]);json_out(['ok'=>true,'message'=>$banned?'User banned from this project.':'Project ban removed.','user'=>au_detail($type,$id,$p)]);}
  if($action==='set-project-role'){au_confirm($body);[$type,$id]=au_target($body);$p=safe_slug((string)($body['project']??''));if($p===''||!project_dir($p))throw new RuntimeException('Choose a valid project.');$enabled=(bool)($body['enabled']??false);$grantType=$type;$grantId=$id;if($type==='guest'){$gc=au_guest_clients($id);$grantType='client';$grantId=(string)($gc[0]??'');if($grantId==='')throw new RuntimeException('Guest has no active browser client to receive project access.');}if($enabled)loom_access_grant_project($p,$grantType,$grantId,'project-admin',$requestClientId,[]);else loom_access_revoke_project($p,$grantType,$grantId,$requestClientId);json_out(['ok'=>true,'message'=>$enabled?'Project Admin granted.':'Project Admin revoked.','user'=>au_detail($type,$id,$p)]);}
  if($action==='set-loom-admin'){au_confirm($body);[$type,$id]=au_target($body);if($type!=='user')throw new RuntimeException('Only a permanent account can be a LOOM Admin.');$enabled=(bool)($body['enabled']??false);if(au_is_system_owner($type,$id)&&!$enabled)throw new RuntimeException('System Owner Admin access cannot be revoked.');if($enabled)loom_access_grant_loom_admin($id,$requestClientId);else loom_access_revoke_loom_admin($id,$requestClientId);json_out(['ok'=>true,'message'=>$enabled?'LOOM Admin granted.':'LOOM Admin revoked.','user'=>au_detail($type,$id,$project)]);}
  if($action==='update-email'){au_confirm($body);[$type,$id]=au_target($body);if($type!=='user')throw new RuntimeException('Permanent account required for email.');au_update_email($id,(string)($body['email']??''));loom_admin_audit('user.email.update',$type,$id,'',[]);json_out(['ok'=>true,'message'=>'Account email updated.','user'=>au_detail($type,$id,$project)]);}
  if($action==='set-password'){au_confirm($body);[$type,$id]=au_target($body);if($type!=='user')throw new RuntimeException('Permanent account required for password.');loom_replace_account_password($id,(string)($body['password']??''),'');loom_admin_audit('user.password.reset',$type,$id,'',['sessionsRevoked'=>true]);json_out(['ok'=>true,'message'=>'Password replaced and prior login sessions revoked.','user'=>au_detail($type,$id,$project)]);}
}catch(Throwable $e){json_out(['ok'=>false,'error'=>$e->getMessage()],409);}
json_out(['ok'=>false,'error'=>'unknown-action'],400);
