<?php
// @loom-file release=0.12.08 revision=2 policy=package-priority
require __DIR__.'/_common.php';
$method=$_SERVER['REQUEST_METHOD']??'GET';$action=(string)($_GET['action']??'state');
if($method==='GET'){
  $clientId=safe_token((string)($_GET['clientId']??''));$project=safe_slug((string)($_GET['project']??''));$scope=strtolower((string)($_GET['scope']??'project'));if($clientId===''||!str_starts_with($clientId,'client_'))json_out(['ok'=>false,'error'=>'Invalid client identity'],400);
  if($action==='image'&&$scope==='global'){$owner=loom_global_profile_owner_for_client($clientId);$f=loom_global_avatar_find($owner['type'],$owner['id']);if(!$f){http_response_code(404);header('Content-Type: text/plain; charset=utf-8');echo 'LOOM profile picture not found';exit;}header('Content-Type: '.$f['mime']);header('Content-Length: '.(string)$f['size']);header('Cache-Control: private, max-age=86400');header('ETag: "'.file_cache_version($f['file']).'"');readfile($f['file']);exit;}
  if($project===''||!project_dir($project))json_out(['ok'=>false,'error'=>'Invalid project'],400);
  if($action==='image'){$owner=loom_avatar_owner_for_client($clientId);$f=loom_avatar_find_file($project,$owner['type'],$owner['id']);if(!$f){http_response_code(404);header('Content-Type: text/plain; charset=utf-8');echo 'Avatar not found';exit;}header('Content-Type: '.$f['mime']);header('Content-Length: '.(string)$f['size']);header('Cache-Control: private, max-age=86400');header('ETag: "'.file_cache_version($f['file']).'"');readfile($f['file']);exit;}
  json_out(['ok'=>true]+loom_avatar_state($clientId,$project));
}
if($method!=='POST')json_out(['ok'=>false,'error'=>'GET or POST required'],405);
$contentType=strtolower((string)($_SERVER['CONTENT_TYPE']??''));
if(str_contains($contentType,'multipart/form-data')){$clientId=safe_token((string)($_POST['clientId']??''));$project=safe_slug((string)($_POST['project']??''));$action=(string)($_POST['action']??'upload');if($action!=='upload')json_out(['ok'=>false,'error'=>'Invalid multipart action'],400);if($clientId===''||!str_starts_with($clientId,'client_')||$project===''||!project_dir($project))json_out(['ok'=>false,'error'=>'Invalid project identity'],400);try{loom_avatar_assert_mutation_access($clientId);}catch(Throwable $e){json_out(['ok'=>false,'error'=>$e->getMessage()],403);}if(!isset($_FILES['avatar'])||!is_array($_FILES['avatar']))json_out(['ok'=>false,'error'=>'No avatar file received'],400);$f=$_FILES['avatar'];if(($f['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)json_out(['ok'=>false,'error'=>'Avatar upload failed'],400);$tmp=(string)$f['tmp_name'];$bytes=(int)($f['size']??0);$fi=new finfo(FILEINFO_MIME_TYPE);$mime=(string)$fi->file($tmp);try{$state=loom_avatar_store_file($clientId,$project,$tmp,$mime,$bytes);json_out(['ok'=>true]+$state);}catch(Throwable $e){json_out(['ok'=>false,'error'=>$e->getMessage()],400);}}
$body=json_decode((string)file_get_contents('php://input'),true);if(!is_array($body))json_out(['ok'=>false,'error'=>'Invalid JSON'],400);$clientId=safe_token((string)($body['clientId']??''));$project=safe_slug((string)($body['project']??''));$action=(string)($body['action']??'');if($clientId===''||!str_starts_with($clientId,'client_')||$project===''||!project_dir($project))json_out(['ok'=>false,'error'=>'Invalid project identity'],400);if($action==='set-mode'){try{$state=loom_avatar_set_mode($clientId,$project,(string)($body['mode']??'auto'));json_out(['ok'=>true]+$state);}catch(Throwable $e){json_out(['ok'=>false,'error'=>$e->getMessage()],400);}}json_out(['ok'=>false,'error'=>'Unknown avatar action'],400);
