<?php
// @loom-file release=0.12.11 revision=2 policy=package-priority
require __DIR__.'/_common.php';
function replay_dir(string $project): string {$d=loom_data_dir().'/replay/'.safe_slug($project);ensure_dir($d);return $d;}
function loom_replay_scrub_event(array $e): array {foreach(['password','secret','token','authorization','cookie'] as $k)unset($e[$k]);if(!empty($e['masked']))$e['value']='[MASKED]';if(isset($e['value'])&&is_string($e['value']))$e['value']=substr($e['value'],0,160);return $e;}
$method=$_SERVER['REQUEST_METHOD']??'GET';
if($method==='POST'){
  $b=json_decode((string)file_get_contents('php://input'),true);if(!is_array($b))json_out(['ok'=>false,'error'=>'Invalid JSON'],400);$project=safe_slug((string)($b['project']??''));$client=safe_token((string)($b['clientId']??''));$session=safe_token((string)($b['sessionId']??''));if(!$project||!project_dir($project)||!$client||!$session)json_out(['ok'=>false,'error'=>'Invalid replay envelope'],400);$events=is_array($b['events']??null)?array_slice($b['events'],0,200):[];$file=replay_dir($project).'/'.gmdate('Y-m-d').'.jsonl';$accepted=0;
  foreach($events as $e){if(!is_array($e))continue;$e=loom_replay_scrub_event($e);$row=['replayId'=>event_id('replay'),'project'=>$project,'clientId'=>$client,'sessionId'=>$session,'userId'=>safe_token((string)($b['userId']??''))?:null,'runtimeId'=>safe_token((string)($b['runtimeId']??''))?:null,'serverTimestamp'=>server_timestamp(),'event'=>$e];@file_put_contents($file,json_encode($row,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)."\n",FILE_APPEND|LOCK_EX);$accepted++;if(loom_db_ready())try{$st=loom_db_pdo(true)->prepare("INSERT IGNORE INTO loom_interaction_events(replay_id,project_slug,session_id,client_id,user_id,event_type,server_timestamp,payload_json) VALUES(?,?,?,?,?,?,?,?)");$st->execute([$row['replayId'],$project,$session,$client,$row['userId'],(string)($e['type']??'interaction'),loom_db_dt($row['serverTimestamp']),json_encode($row,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)]);}catch(Throwable $x){}
  }json_out(['ok'=>true,'accepted'=>$accepted]);
}
if(!loom_request_is_admin())json_out(['ok'=>false,'error'=>'admin-access-required'],403);$project=safe_slug((string)($_GET['project']??''));$session=safe_token((string)($_GET['sessionId']??''));$limit=max(1,min(5000,(int)($_GET['limit']??1000)));$rows=[];foreach(glob(replay_dir($project).'/*.jsonl')?:[] as $file)foreach(@file($file,FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES)?:[] as $line){$r=json_decode($line,true);if(!is_array($r))continue;if($session!==''&&($r['sessionId']??'')!==$session)continue;$rows[]=$r;if(count($rows)>=$limit)break 2;}json_out(['ok'=>true,'rows'=>$rows,'note'=>'Interaction replay capture foundation only; classified sensitive fields are masked or omitted before storage.']);
